version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - noctx
    - unconvert
  exclusions:
    paths:
      - internal/gen
      - botclient
    rules:
      - path: _test\.go
        linters:
          - gosec
          - noctx

formatters:
  enable:
    - gofmt
