/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build information */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with username and password; sets the session cookies */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew the session tokens (called silently by clients)
         * @description The refresh token comes from its cookie (web) or the request body (native clients).
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a password from an activation link and sign in */
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change display name, time zone or notice settings */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the password; keeps this session and signs out the others */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active sessions of the user */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign out one session */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions/revoke-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out everywhere */
        post: operations["revokeAllSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Linked chat identities */
        get: operations["listIdentities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/identities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink a chat identity */
        delete: operations["unlinkIdentity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/pairing-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a one-time code to link a chat with `!link CODE` */
        post: operations["createPairingCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bot-instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bot instances the user can link to, with their online status */
        get: operations["listBotInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Inbox, newest first */
        get: operations["listInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One note with its parts */
        get: operations["getNote"];
        put?: never;
        post?: never;
        /** Permanently delete a note that is in the Trash */
        delete: operations["deleteNotePermanently"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The user's pages in order */
        get: operations["listPages"];
        put?: never;
        /** Create a page */
        post: operations["createPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a page; its notes return to the Inbox */
        delete: operations["deletePage"];
        options?: never;
        head?: never;
        /** Rename, reorder or archive a page */
        patch: operations["updatePage"];
        trace?: never;
    };
    "/api/v1/pages/{id}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A page's categories with their first notes and counts, in one call */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a category on a page */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a category; its notes return to the Inbox */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /** Rename a category, reorder it, or move it to another page */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/api/v1/categories/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notes of a category in their manual order */
        get: operations["listCategoryNotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a note in the app, in the Inbox or in a category */
        post: operations["createNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a note to a category (at a position) or back to the Inbox */
        post: operations["moveNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss a note (soft delete); undo with restore */
        post: operations["dismissNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a dismissed note to where it was (or the Inbox) */
        post: operations["restoreNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a text or attachment part to a note */
        post: operations["addNotePart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}/parts/{partId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a part (a note always keeps at least one) */
        delete: operations["deleteNotePart"];
        options?: never;
        head?: never;
        /** Edit the text of a part (the latest edit wins; nothing is lost) */
        patch: operations["editNotePart"];
        trace?: never;
    };
    "/api/v1/notes/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every text version of every part of a note */
        get: operations["getNoteHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dismissed notes, newest first */
        get: operations["listTrash"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a file; supports Range and conditional requests */
        get: operations["downloadAttachment"];
        /**
         * Upload a file (raw body, streamed); idempotent on the id
         * @description The body is the file itself with `Content-Type: application/octet-stream`; `Content-Length`
         *     is required. The name goes in `X-Filename` (percent-encoded), the media type in `X-Media-Type`.
         *     The attachment is unlinked until a note part references it; unused ones are removed after an hour.
         */
        put: operations["uploadAttachment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text search over the user's notes
         * @description Matches note text and attachment filenames, ignoring case and accents, with prefix matching
         *     for the last words typed. Results are ranked; `snippet` marks matches with the private-use
         *     characters U+E000 (start) and U+E001 (end), which the client turns into highlights.
         */
        get: operations["searchNotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream of change notifications
         * @description Hand-written handler (not generated). `event: change` with `id: <seq>` per change,
         *     `event: resync` when the client must refetch, `event: reconnect` before a server shutdown;
         *     a comment line every 25 seconds. Resumes from `Last-Event-ID`.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The change feed after a cursor */
        get: operations["listChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts with status and storage use (metadata only) */
        get: operations["adminListUsers"];
        put?: never;
        /** Create a pending account; issue an activation link separately */
        post: operations["adminCreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Disable or enable an account, or set its quota */
        patch: operations["adminUpdateUser"];
        trace?: never;
    };
    "/api/v1/admin/users/{id}/activation-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue an activation link (clears the password, signs the user out everywhere) */
        post: operations["adminIssueActivationLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bot-instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registered bot instances */
        get: operations["adminListBotInstances"];
        put?: never;
        /** Register a bot instance */
        post: operations["adminCreateBotInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bot-instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Enable or disable an instance */
        patch: operations["adminUpdateBotInstance"];
        trace?: never;
    };
    "/api/v1/admin/bot-instances/{id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a credential; the secret is shown once */
        post: operations["adminCreateBotCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bot-instances/{id}/credentials/{credentialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disable a credential */
        delete: operations["adminDisableBotCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Version: {
            version: string;
        };
        /** @description RFC 9457 problem details */
        Problem: {
            type?: string;
            title: string;
            status: number;
            code?: string;
            detail?: string;
            request_id?: string;
        };
        LoginRequest: {
            username: string;
            password: string;
            /** @default true */
            remember: boolean;
            /**
             * @default web
             * @enum {string}
             */
            client_kind: "web" | "native";
        };
        RefreshRequest: {
            refresh_token?: string;
        };
        ActivateRequest: {
            token: string;
            password: string;
        };
        AuthResult: {
            user: components["schemas"]["Me"];
            /**
             * Format: date-time
             * @description When the access token lapses
             */
            expires_at: string;
            /** @description Only for native clients */
            access_token?: string;
            /** @description Only for native clients */
            refresh_token?: string;
        };
        Me: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
            is_admin: boolean;
            timezone: string;
            settings: {
                [key: string]: unknown;
            };
        };
        UpdateMe: {
            display_name?: string;
            timezone?: string;
            settings?: {
                [key: string]: unknown;
            };
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        Session: {
            /** Format: uuid */
            id: string;
            label: string;
            client_kind: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at: string;
            /** Format: date-time */
            expires_at: string;
            current: boolean;
        };
        Identity: {
            /** Format: uuid */
            id: string;
            bot_instance_name: string;
            bot_type: string;
            external_user_id: string;
            reminder_target: boolean;
            /** Format: date-time */
            linked_at: string;
        };
        PairingCode: {
            /** @example K7QM-2XPA */
            code: string;
            /** Format: date-time */
            expires_at: string;
        };
        BotInstanceSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            type: string;
            online: boolean;
        };
        NotePart: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "text" | "attachment" | "failed_attachment" | "unsupported";
            text?: string;
            attachment?: components["schemas"]["AttachmentRef"];
            failed?: components["schemas"]["FailedAttachment"];
            /** @enum {string} */
            attach_reason: "first" | "reply" | "thread" | "media-adjacency" | "app";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            text_edited_at?: string;
            /** @description Present for parts that came from a chat */
            source_bot_type?: string;
        };
        AttachmentRef: {
            /** Format: uuid */
            id: string;
            filename: string;
            media_type: string;
            /** Format: int64 */
            size: number;
        };
        FailedAttachment: {
            filename: string;
            /** Format: int64 */
            size?: number;
            reason: string;
        };
        Note: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            category_id?: string | null;
            /** @enum {string} */
            state: "active" | "deleted";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            deleted_at?: string;
            previous_location?: components["schemas"]["PreviousLocation"];
            version: number;
            parts: components["schemas"]["NotePart"][];
        };
        NotePage: {
            items: components["schemas"]["Note"][];
            next_cursor?: string;
            /** Format: int64 */
            total?: number;
        };
        Page: {
            /** Format: uuid */
            id: string;
            name: string;
            archived?: boolean;
            version: number;
            /** @description Only in the page list, in order: for navigation and the Move-to menu */
            categories?: {
                /** Format: uuid */
                id: string;
                name: string;
            }[];
        };
        CreatePage: {
            /**
             * Format: uuid
             * @description Client-generated id; repeating it returns the existing page
             */
            id?: string;
            name: string;
            /**
             * Format: uuid
             * @description Place after this page; default is the end
             */
            after_id?: string | null;
        };
        UpdatePage: {
            name?: string;
            archived?: boolean;
            /** Format: uuid */
            before_id?: string | null;
            /** Format: uuid */
            after_id?: string | null;
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            page_id: string;
            name: string;
            version: number;
        };
        CreateCategory: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            page_id: string;
            name: string;
            /** Format: uuid */
            after_id?: string | null;
        };
        UpdateCategory: {
            name?: string;
            /**
             * Format: uuid
             * @description Move the category to another page
             */
            page_id?: string;
            /** Format: uuid */
            before_id?: string | null;
            /** Format: uuid */
            after_id?: string | null;
        };
        Deleted: {
            /** @description Notes that returned to the Inbox */
            moved_notes: number;
        };
        Board: {
            page: components["schemas"]["Page"];
            /** Format: int64 */
            inbox_total: number;
            categories: components["schemas"]["BoardCategory"][];
        };
        BoardCategory: {
            category: components["schemas"]["Category"];
            notes: components["schemas"]["Note"][];
            /** Format: int64 */
            total: number;
            next_cursor?: string;
        };
        NewPartInput: {
            /** @enum {string} */
            type: "text" | "attachment";
            text?: string;
            /**
             * Format: uuid
             * @description An attachment uploaded earlier and not yet used
             */
            attachment_id?: string;
        };
        CreateNote: {
            /**
             * Format: uuid
             * @description Client-generated id; repeating it with the same content returns the note
             */
            id?: string;
            /**
             * Format: uuid
             * @description null puts the note in the Inbox
             */
            category_id?: string | null;
            /** Format: uuid */
            before_id?: string | null;
            /** Format: uuid */
            after_id?: string | null;
            parts: components["schemas"]["NewPartInput"][];
        };
        MoveNote: {
            /**
             * Format: uuid
             * @description null moves the note to the Inbox
             */
            category_id: string | null;
            /**
             * Format: uuid
             * @description The note that should come right after it
             */
            before_id?: string | null;
            /**
             * Format: uuid
             * @description The note that should come right before it
             */
            after_id?: string | null;
        };
        NewPart: {
            /** @enum {string} */
            type: "text" | "attachment";
            text?: string;
            /** Format: uuid */
            attachment_id?: string;
        };
        EditPart: {
            text: string;
            /** @description The note version the edit is based on */
            base_version?: number;
        };
        EditResult: {
            note: components["schemas"]["Note"];
            /** @description True when the note changed since base_version; the overwritten text stays in history */
            stale: boolean;
        };
        NoteHistory: {
            parts: {
                /** Format: uuid */
                part_id: string;
                versions: components["schemas"]["PartVersion"][];
            }[];
        };
        PartVersion: {
            /** Format: uuid */
            id: string;
            text: string;
            /** @enum {string} */
            origin: "chat" | "app";
            /** Format: date-time */
            edited_at: string;
            /** @description false for a late chat edit that did not overwrite a newer text */
            applied: boolean;
        };
        /** @description Where a dismissed note came from (Trash view) */
        PreviousLocation: {
            /** Format: uuid */
            category_id?: string;
            category_name?: string;
            /** Format: uuid */
            page_id?: string;
            page_name?: string;
        };
        SearchHit: {
            note: components["schemas"]["Note"];
            snippet: string;
            location?: components["schemas"]["PreviousLocation"];
        };
        SearchPage: {
            items: components["schemas"]["SearchHit"][];
            next_cursor?: string;
        };
        Change: {
            /** Format: int64 */
            seq: number;
            entity_type: string;
            /** Format: uuid */
            entity_id: string;
            /** @enum {string} */
            op: "upsert" | "delete";
            version?: number;
        };
        ChangePage: {
            items: components["schemas"]["Change"][];
            /** @description Pass this back to get the next changes */
            cursor: string;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
            /** @enum {string} */
            status: "pending" | "active" | "disabled" | "deleting";
            is_admin: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            used_bytes: number;
            /** Format: int64 */
            quota_bytes?: number | null;
        };
        CreateUser: {
            username: string;
            display_name?: string;
            email?: string;
            timezone?: string;
        };
        AdminUpdateUser: {
            disabled?: boolean;
            /**
             * Format: int64
             * @description Set the storage quota
             */
            quota_bytes?: number;
            /** @description Return to the deployment default quota */
            reset_quota?: boolean;
        };
        ActivationLink: {
            token: string;
            /** @description Path to open on the app host, e.g. /activate#TOKEN */
            path: string;
            /** Format: date-time */
            expires_at: string;
        };
        AdminBotInstance: {
            /** Format: uuid */
            id: string;
            type: string;
            name: string;
            identity_domain: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            last_seen_at?: string;
            /** Format: date-time */
            created_at: string;
            credentials?: components["schemas"]["BotCredentialInfo"][];
        };
        CreateBotInstance: {
            type: string;
            name: string;
            identity_domain?: string;
        };
        BotCredentialInfo: {
            /** Format: uuid */
            id: string;
            client_id: string;
            scopes: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            disabled_at?: string;
        };
        BotCredential: {
            /** Format: uuid */
            id: string;
            client_id: string;
            /** @description The value the bot sends in Authorization; shown once */
            bearer: string;
        };
    };
    responses: {
        /** @description Error (RFC 9457) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Id: string;
        PartId: string;
        Limit: number;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Renewed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateRequest"];
            };
        };
        responses: {
            /** @description Activated and signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMe"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Session"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default false */
                    keep_current?: boolean;
                };
            };
        };
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listIdentities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Identity"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    unlinkIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unlinked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    createPairingCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    bot_instance_id: string;
                };
            };
        };
        responses: {
            /** @description Created; the code is shown only now */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingCode"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listBotInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["BotInstanceSummary"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listInbox: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of notes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotePage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The note */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteNotePermanently: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listPages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Page"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePage"];
            };
        };
        responses: {
            /** @description Created (or the existing page for a repeated client id) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deletePage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deleted"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updatePage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePage"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getBoard: {
        parameters: {
            query?: {
                notes_per_category?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The board */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategory"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deleted"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategory"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listCategoryNotes: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of notes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotePage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createNote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNote"];
            };
        };
        responses: {
            /** @description Created (or the existing note for a repeated client id with the same content) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    moveNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveNote"];
            };
        };
        responses: {
            /** @description The moved note */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    dismissNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The dismissed note */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    restoreNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The restored note */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    addNotePart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPart"];
            };
        };
        responses: {
            /** @description The updated note */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteNotePart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                partId: components["parameters"]["PartId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated note */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    editNotePart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                partId: components["parameters"]["PartId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditPart"];
            };
        };
        responses: {
            /** @description The updated note; stale says another edit happened since base_version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getNoteHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History, newest first per part */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteHistory"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTrash: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of dismissed notes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotePage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    downloadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file. Always sent with nosniff, a sandbox CSP and `private, no-cache`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    uploadAttachment: {
        parameters: {
            query?: never;
            header: {
                "X-Filename": string;
                "X-Media-Type"?: string;
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentRef"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    searchNotes: {
        parameters: {
            query: {
                q: string;
                scope?: "active" | "trash" | "all";
                page_id?: string;
                category_id?: string;
                has_attachment?: boolean;
                has_reminder?: boolean;
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    listChanges: {
        parameters: {
            query?: {
                /** @description Opaque cursor from an earlier response; omit for the current position */
                cursor?: string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Changes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePage"];
                };
            };
            /** @description The cursor is older than the retained changes; refetch everything */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminUser"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    adminCreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUser"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    adminUpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateUser"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    adminIssueActivationLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The link, shown once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationLink"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    adminListBotInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminBotInstance"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    adminCreateBotInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBotInstance"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBotInstance"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    adminUpdateBotInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "active" | "disabled";
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    adminCreateBotCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    scopes?: ("ingest" | "deliver")[];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotCredential"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    adminDisableBotCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                credentialId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disabled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
}
