// Package botclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package botclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventKind.
const (
	MessageCreated EventKind = "message_created"
	MessageDeleted EventKind = "message_deleted"
	MessageEdited  EventKind = "message_edited"
)

// Valid indicates whether the value is a known member of the EventKind enum.
func (e EventKind) Valid() bool {
	switch e {
	case MessageCreated:
		return true
	case MessageDeleted:
		return true
	case MessageEdited:
		return true
	default:
		return false
	}
}

// Defines values for EventPartType.
const (
	Attachment       EventPartType = "attachment"
	AttachmentFailed EventPartType = "attachment_failed"
	Text             EventPartType = "text"
	Unsupported      EventPartType = "unsupported"
)

// Valid indicates whether the value is a known member of the EventPartType enum.
func (e EventPartType) Valid() bool {
	switch e {
	case Attachment:
		return true
	case AttachmentFailed:
		return true
	case Text:
		return true
	case Unsupported:
		return true
	default:
		return false
	}
}

// Defines values for EventResultResult.
const (
	Appended EventResultResult = "appended"
	Created  EventResultResult = "created"
	Ignored  EventResultResult = "ignored"
	Rejected EventResultResult = "rejected"
	Removed  EventResultResult = "removed"
	Updated  EventResultResult = "updated"
)

// Valid indicates whether the value is a known member of the EventResultResult enum.
func (e EventResultResult) Valid() bool {
	switch e {
	case Appended:
		return true
	case Created:
		return true
	case Ignored:
		return true
	case Rejected:
		return true
	case Removed:
		return true
	case Updated:
		return true
	default:
		return false
	}
}

// Defines values for OutboxItemKind.
const (
	Lifecycle OutboxItemKind = "lifecycle"
	Notice    OutboxItemKind = "notice"
	Reminder  OutboxItemKind = "reminder"
)

// Valid indicates whether the value is a known member of the OutboxItemKind enum.
func (e OutboxItemKind) Valid() bool {
	switch e {
	case Lifecycle:
		return true
	case Notice:
		return true
	case Reminder:
		return true
	default:
		return false
	}
}

// Defines values for OutboxResultState.
const (
	Delivered       OutboxResultState = "delivered"
	FailedPermanent OutboxResultState = "failed_permanent"
	FailedTransient OutboxResultState = "failed_transient"
)

// Valid indicates whether the value is a known member of the OutboxResultState enum.
func (e OutboxResultState) Valid() bool {
	switch e {
	case Delivered:
		return true
	case FailedPermanent:
		return true
	case FailedTransient:
		return true
	default:
		return false
	}
}

// Command defines model for Command.
type Command struct {
	Args         *string    `json:"args,omitempty"`
	Command      string     `json:"command"`
	Conversation string     `json:"conversation"`
	MessageId    *string    `json:"message_id,omitempty"`
	ReplyTo      *string    `json:"reply_to,omitempty"`
	Sender       string     `json:"sender"`
	Timestamp    *time.Time `json:"timestamp,omitempty"`
}

// CommandResult defines model for CommandResult.
type CommandResult struct {
	Feedback Feedback `json:"feedback"`
	Ok       bool     `json:"ok"`
}

// Event defines model for Event.
type Event struct {
	Conversation string `json:"conversation"`

	// EventId Unique per platform event; the dedupe key
	EventId string    `json:"event_id"`
	Kind    EventKind `json:"kind"`

	// MessageId For edits and deletes the ORIGINAL message id
	MessageId string       `json:"message_id"`
	Parts     *[]EventPart `json:"parts,omitempty"`
	RelatesTo *struct {
		ReplyTo *string `json:"reply_to,omitempty"`
		Thread  *string `json:"thread,omitempty"`
	} `json:"relates_to,omitempty"`

	// Sender Verified by the bot from platform metadata
	Sender string `json:"sender"`

	// Timestamp Platform event time
	Timestamp time.Time `json:"timestamp"`
}

// EventKind defines model for Event.Kind.
type EventKind string

// EventPart defines model for EventPart.
type EventPart struct {
	Description *string             `json:"description,omitempty"`
	Filename    *string             `json:"filename,omitempty"`
	MediaType   *string             `json:"media_type,omitempty"`
	Reason      *string             `json:"reason,omitempty"`
	Size        *int64              `json:"size,omitempty"`
	Text        *string             `json:"text,omitempty"`
	Type        EventPartType       `json:"type"`
	UploadId    *openapi_types.UUID `json:"upload_id,omitempty"`
}

// EventPartType defines model for EventPart.Type.
type EventPartType string

// EventResult defines model for EventResult.
type EventResult struct {
	Code     *string             `json:"code,omitempty"`
	Feedback Feedback            `json:"feedback"`
	NoteId   *openapi_types.UUID `json:"note_id,omitempty"`
	Result   EventResultResult   `json:"result"`
}

// EventResultResult defines model for EventResult.Result.
type EventResultResult string

// Feedback defines model for Feedback.
type Feedback struct {
	// React Reaction to add to the source message, e.g. "ok"
	React *string `json:"react,omitempty"`

	// ReplyText Text to send back to the user
	ReplyText *string `json:"reply_text,omitempty"`
}

// IdentityStatus defines model for IdentityStatus.
type IdentityStatus struct {
	Conversation *string    `json:"conversation,omitempty"`
	Linked       bool       `json:"linked"`
	LinkedAt     *time.Time `json:"linked_at,omitempty"`
}

// OutboxItem defines model for OutboxItem.
type OutboxItem struct {
	Attempts       int        `json:"attempts"`
	ConversationId string     `json:"conversation_id"`
	DueAt          *time.Time `json:"due_at,omitempty"`
	ExternalUserId string     `json:"external_user_id"`

	// Id Also the idempotency key for the platform send (BOT-13)
	Id   openapi_types.UUID `json:"id"`
	Kind OutboxItemKind     `json:"kind"`

	// Payload notice/reminder: {text, ...}; lifecycle: {reason: unlinked | user_deleted}
	Payload map[string]interface{} `json:"payload"`
}

// OutboxItemKind defines model for OutboxItem.Kind.
type OutboxItemKind string

// OutboxResult defines model for OutboxResult.
type OutboxResult struct {
	MessageIds *[]string         `json:"message_ids,omitempty"`
	Reason     *string           `json:"reason,omitempty"`
	State      OutboxResultState `json:"state"`
}

// OutboxResultState defines model for OutboxResult.State.
type OutboxResultState string

// Problem defines model for Problem.
type Problem struct {
	Code      *string `json:"code,omitempty"`
	Detail    *string `json:"detail,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      *string `json:"type,omitempty"`
}

// Upload defines model for Upload.
type Upload struct {
	Filename  string             `json:"filename"`
	Id        openapi_types.UUID `json:"id"`
	MediaType string             `json:"media_type"`
	Size      int64              `json:"size"`
}

// Version defines model for Version.
type Version struct {
	Version string `json:"version"`
}

// ClaimOutboxParams defines parameters for ClaimOutbox.
type ClaimOutboxParams struct {
	Wait  *int `form:"wait,omitempty" json:"wait,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PutUploadParams defines parameters for PutUpload.
type PutUploadParams struct {
	XExternalUser string  `json:"X-External-User"`
	XFilename     string  `json:"X-Filename"`
	XMediaType    *string `json:"X-Media-Type,omitempty"`
}

// PostCommandJSONRequestBody defines body for PostCommand for application/json ContentType.
type PostCommandJSONRequestBody = Command

// PostEventJSONRequestBody defines body for PostEvent for application/json ContentType.
type PostEventJSONRequestBody = Event

// PostOutboxResultJSONRequestBody defines body for PostOutboxResult for application/json ContentType.
type PostOutboxResultJSONRequestBody = OutboxResult

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PostCommandWithBody A chat command (link, unlink, help, ...)
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /bot/v1/commands (the `PostCommand` operationId).
	PostCommandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCommand A chat command (link, unlink, help, ...)
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /bot/v1/commands (the `PostCommand` operationId).
	PostCommand(ctx context.Context, body PostCommandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConversationCursor The platform time of the newest message Core holds for a conversation
	//
	// Lets a bot that lost its own position resume after the right message instead of replaying everything.
	//
	// Corresponds with GET /bot/v1/conversations/{id}/cursor (the `GetConversationCursor` operationId).
	GetConversationCursor(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEventWithBody A normalised chat event (created, edited or deleted message)
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /bot/v1/events (the `PostEvent` operationId).
	PostEventWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEvent A normalised chat event (created, edited or deleted message)
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /bot/v1/events (the `PostEvent` operationId).
	PostEvent(ctx context.Context, body PostEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHeartbeat Liveness signal for the admin's bot status
	//
	// Corresponds with POST /bot/v1/heartbeat (the `PostHeartbeat` operationId).
	PostHeartbeat(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIdentity Whether a chat identity is linked (nothing about the user)
	//
	// Corresponds with GET /bot/v1/identities/{external_user_id} (the `GetIdentity` operationId).
	GetIdentity(ctx context.Context, externalUserId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ClaimOutbox Long-poll the outbox for items addressed to this bot instance
	//
	// Claims queued items with a 60-second lease. Waits up to `wait` seconds when nothing is
	// available. An item that is not acknowledged before its lease expires is offered again;
	// an expired lease does not count as a delivery attempt.
	//
	// Corresponds with GET /bot/v1/outbox (the `ClaimOutbox` operationId).
	ClaimOutbox(ctx context.Context, params *ClaimOutboxParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOutboxAttachment Download a file that a claimed reminder lists, to send it into the chat
	//
	// Only files listed in the payload of an item this bot instance has claimed, and only while
	// the claim lasts. A bot key never reads anything else of a user's files (BOT-15, SEC-BOT-3).
	//
	// Corresponds with GET /bot/v1/outbox/{id}/attachments/{attachmentId} (the `GetOutboxAttachment` operationId).
	GetOutboxAttachment(ctx context.Context, id openapi_types.UUID, attachmentId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOutboxResultWithBody Report what happened to a claimed outbox item
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /bot/v1/outbox/{id}/result (the `PostOutboxResult` operationId).
	PostOutboxResultWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOutboxResult Report what happened to a claimed outbox item
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /bot/v1/outbox/{id}/result (the `PostOutboxResult` operationId).
	PostOutboxResult(ctx context.Context, id openapi_types.UUID, body PostOutboxResultJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutUploadWithBody Stream an attachment for a linked chat identity (already decrypted by the bot)
	//
	// Same storage path and quota as the user upload. The body is the raw file with
	// `Content-Type: application/octet-stream` and a required `Content-Length`. The attachment
	// stays unlinked until an event references it by `upload_id`; unused ones are removed after an hour.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /bot/v1/uploads/{id} (the `PutUpload` operationId).
	PutUploadWithBody(ctx context.Context, id openapi_types.UUID, params *PutUploadParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBotVersion Build information
	//
	// Corresponds with GET /bot/v1/version (the `GetBotVersion` operationId).
	GetBotVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostCommandWithBody A chat command (link, unlink, help, ...)
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /bot/v1/commands (the `PostCommand` operationId).
func (c *Client) PostCommandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCommandRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCommand A chat command (link, unlink, help, ...)
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /bot/v1/commands (the `PostCommand` operationId).
func (c *Client) PostCommand(ctx context.Context, body PostCommandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCommandRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetConversationCursor The platform time of the newest message Core holds for a conversation
//
// Lets a bot that lost its own position resume after the right message instead of replaying everything.
//
// Corresponds with GET /bot/v1/conversations/{id}/cursor (the `GetConversationCursor` operationId).
func (c *Client) GetConversationCursor(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConversationCursorRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostEventWithBody A normalised chat event (created, edited or deleted message)
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /bot/v1/events (the `PostEvent` operationId).
func (c *Client) PostEventWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEventRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostEvent A normalised chat event (created, edited or deleted message)
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /bot/v1/events (the `PostEvent` operationId).
func (c *Client) PostEvent(ctx context.Context, body PostEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEventRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostHeartbeat Liveness signal for the admin's bot status
//
// Corresponds with POST /bot/v1/heartbeat (the `PostHeartbeat` operationId).
func (c *Client) PostHeartbeat(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHeartbeatRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetIdentity Whether a chat identity is linked (nothing about the user)
//
// Corresponds with GET /bot/v1/identities/{external_user_id} (the `GetIdentity` operationId).
func (c *Client) GetIdentity(ctx context.Context, externalUserId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIdentityRequest(c.Server, externalUserId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ClaimOutbox Long-poll the outbox for items addressed to this bot instance
//
// Claims queued items with a 60-second lease. Waits up to `wait` seconds when nothing is
// available. An item that is not acknowledged before its lease expires is offered again;
// an expired lease does not count as a delivery attempt.
//
// Corresponds with GET /bot/v1/outbox (the `ClaimOutbox` operationId).
func (c *Client) ClaimOutbox(ctx context.Context, params *ClaimOutboxParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClaimOutboxRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetOutboxAttachment Download a file that a claimed reminder lists, to send it into the chat
//
// Only files listed in the payload of an item this bot instance has claimed, and only while
// the claim lasts. A bot key never reads anything else of a user's files (BOT-15, SEC-BOT-3).
//
// Corresponds with GET /bot/v1/outbox/{id}/attachments/{attachmentId} (the `GetOutboxAttachment` operationId).
func (c *Client) GetOutboxAttachment(ctx context.Context, id openapi_types.UUID, attachmentId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOutboxAttachmentRequest(c.Server, id, attachmentId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostOutboxResultWithBody Report what happened to a claimed outbox item
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /bot/v1/outbox/{id}/result (the `PostOutboxResult` operationId).
func (c *Client) PostOutboxResultWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOutboxResultRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostOutboxResult Report what happened to a claimed outbox item
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /bot/v1/outbox/{id}/result (the `PostOutboxResult` operationId).
func (c *Client) PostOutboxResult(ctx context.Context, id openapi_types.UUID, body PostOutboxResultJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOutboxResultRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutUploadWithBody Stream an attachment for a linked chat identity (already decrypted by the bot)
//
// Same storage path and quota as the user upload. The body is the raw file with
// `Content-Type: application/octet-stream` and a required `Content-Length`. The attachment
// stays unlinked until an event references it by `upload_id`; unused ones are removed after an hour.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /bot/v1/uploads/{id} (the `PutUpload` operationId).
func (c *Client) PutUploadWithBody(ctx context.Context, id openapi_types.UUID, params *PutUploadParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutUploadRequestWithBody(c.Server, id, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetBotVersion Build information
//
// Corresponds with GET /bot/v1/version (the `GetBotVersion` operationId).
func (c *Client) GetBotVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBotVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostCommandRequest calls the generic PostCommand builder with application/json body
func NewPostCommandRequest(server string, body PostCommandJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCommandRequestWithBody(server, "application/json", bodyReader)
}

// NewPostCommandRequestWithBody constructs an http.Request for the PostCommand method, with any body, and a specified content type
func NewPostCommandRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot/v1/commands")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetConversationCursorRequest constructs an http.Request for the GetConversationCursor method
func NewGetConversationCursorRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot/v1/conversations/%s/cursor", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostEventRequest calls the generic PostEvent builder with application/json body
func NewPostEventRequest(server string, body PostEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostEventRequestWithBody(server, "application/json", bodyReader)
}

// NewPostEventRequestWithBody constructs an http.Request for the PostEvent method, with any body, and a specified content type
func NewPostEventRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot/v1/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostHeartbeatRequest constructs an http.Request for the PostHeartbeat method
func NewPostHeartbeatRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot/v1/heartbeat")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetIdentityRequest constructs an http.Request for the GetIdentity method
func NewGetIdentityRequest(server string, externalUserId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "external_user_id", externalUserId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot/v1/identities/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewClaimOutboxRequest constructs an http.Request for the ClaimOutbox method
func NewClaimOutboxRequest(server string, params *ClaimOutboxParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot/v1/outbox")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Wait != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "wait", *params.Wait, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetOutboxAttachmentRequest constructs an http.Request for the GetOutboxAttachment method
func NewGetOutboxAttachmentRequest(server string, id openapi_types.UUID, attachmentId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "attachmentId", attachmentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot/v1/outbox/%s/attachments/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostOutboxResultRequest calls the generic PostOutboxResult builder with application/json body
func NewPostOutboxResultRequest(server string, id openapi_types.UUID, body PostOutboxResultJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOutboxResultRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPostOutboxResultRequestWithBody constructs an http.Request for the PostOutboxResult method, with any body, and a specified content type
func NewPostOutboxResultRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot/v1/outbox/%s/result", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutUploadRequestWithBody constructs an http.Request for the PutUpload method, with any body, and a specified content type
func NewPutUploadRequestWithBody(server string, id openapi_types.UUID, params *PutUploadParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot/v1/uploads/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-External-User", params.XExternalUser, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-External-User", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Filename", params.XFilename, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Filename", headerParam1)

		if params.XMediaType != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "X-Media-Type", *params.XMediaType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Media-Type", headerParam2)
		}

	}

	return req, nil
}

// NewGetBotVersionRequest constructs an http.Request for the GetBotVersion method
func NewGetBotVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot/v1/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PostCommandWithBodyWithResponse A chat command (link, unlink, help, ...)
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /bot/v1/commands (the `PostCommand` operationId).
	PostCommandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCommandResponse, error)

	// PostCommandWithResponse A chat command (link, unlink, help, ...)
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /bot/v1/commands (the `PostCommand` operationId).
	PostCommandWithResponse(ctx context.Context, body PostCommandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCommandResponse, error)

	// GetConversationCursorWithResponse The platform time of the newest message Core holds for a conversation
	//
	// Lets a bot that lost its own position resume after the right message instead of replaying everything.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /bot/v1/conversations/{id}/cursor (the `GetConversationCursor` operationId).
	GetConversationCursorWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetConversationCursorResponse, error)

	// PostEventWithBodyWithResponse A normalised chat event (created, edited or deleted message)
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /bot/v1/events (the `PostEvent` operationId).
	PostEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEventResponse, error)

	// PostEventWithResponse A normalised chat event (created, edited or deleted message)
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /bot/v1/events (the `PostEvent` operationId).
	PostEventWithResponse(ctx context.Context, body PostEventJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEventResponse, error)

	// PostHeartbeatWithResponse Liveness signal for the admin's bot status
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /bot/v1/heartbeat (the `PostHeartbeat` operationId).
	PostHeartbeatWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostHeartbeatResponse, error)

	// GetIdentityWithResponse Whether a chat identity is linked (nothing about the user)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /bot/v1/identities/{external_user_id} (the `GetIdentity` operationId).
	GetIdentityWithResponse(ctx context.Context, externalUserId string, reqEditors ...RequestEditorFn) (*GetIdentityResponse, error)

	// ClaimOutboxWithResponse Long-poll the outbox for items addressed to this bot instance
	//
	// Claims queued items with a 60-second lease. Waits up to `wait` seconds when nothing is
	// available. An item that is not acknowledged before its lease expires is offered again;
	// an expired lease does not count as a delivery attempt.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /bot/v1/outbox (the `ClaimOutbox` operationId).
	ClaimOutboxWithResponse(ctx context.Context, params *ClaimOutboxParams, reqEditors ...RequestEditorFn) (*ClaimOutboxResponse, error)

	// GetOutboxAttachmentWithResponse Download a file that a claimed reminder lists, to send it into the chat
	//
	// Only files listed in the payload of an item this bot instance has claimed, and only while
	// the claim lasts. A bot key never reads anything else of a user's files (BOT-15, SEC-BOT-3).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /bot/v1/outbox/{id}/attachments/{attachmentId} (the `GetOutboxAttachment` operationId).
	GetOutboxAttachmentWithResponse(ctx context.Context, id openapi_types.UUID, attachmentId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetOutboxAttachmentResponse, error)

	// PostOutboxResultWithBodyWithResponse Report what happened to a claimed outbox item
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /bot/v1/outbox/{id}/result (the `PostOutboxResult` operationId).
	PostOutboxResultWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOutboxResultResponse, error)

	// PostOutboxResultWithResponse Report what happened to a claimed outbox item
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /bot/v1/outbox/{id}/result (the `PostOutboxResult` operationId).
	PostOutboxResultWithResponse(ctx context.Context, id openapi_types.UUID, body PostOutboxResultJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOutboxResultResponse, error)

	// PutUploadWithBodyWithResponse Stream an attachment for a linked chat identity (already decrypted by the bot)
	//
	// Same storage path and quota as the user upload. The body is the raw file with
	// `Content-Type: application/octet-stream` and a required `Content-Length`. The attachment
	// stays unlinked until an event references it by `upload_id`; unused ones are removed after an hour.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /bot/v1/uploads/{id} (the `PutUpload` operationId).
	PutUploadWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, params *PutUploadParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutUploadResponse, error)

	// GetBotVersionWithResponse Build information
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /bot/v1/version (the `GetBotVersion` operationId).
	GetBotVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBotVersionResponse, error)
}

type PostCommandResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CommandResult
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostCommandResponse) GetJSON200() *CommandResult {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r PostCommandResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r PostCommandResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostCommandResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCommandResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostCommandResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetConversationCursorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		LastMessageAt *time.Time `json:"last_message_at,omitempty"`
	}
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetConversationCursorResponse) GetJSON200() *struct {
	LastMessageAt *time.Time `json:"last_message_at,omitempty"`
} {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetConversationCursorResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetConversationCursorResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetConversationCursorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConversationCursorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetConversationCursorResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *EventResult
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostEventResponse) GetJSON200() *EventResult {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r PostEventResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r PostEventResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostEventResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostHeartbeatResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r PostHeartbeatResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r PostHeartbeatResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostHeartbeatResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHeartbeatResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostHeartbeatResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetIdentityResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *IdentityStatus
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetIdentityResponse) GetJSON200() *IdentityStatus {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetIdentityResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetIdentityResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetIdentityResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIdentityResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetIdentityResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ClaimOutboxResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Items []OutboxItem `json:"items"`
	}
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ClaimOutboxResponse) GetJSON200() *struct {
	Items []OutboxItem `json:"items"`
} {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r ClaimOutboxResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r ClaimOutboxResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ClaimOutboxResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ClaimOutboxResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ClaimOutboxResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetOutboxAttachmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetOutboxAttachmentResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetOutboxAttachmentResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetOutboxAttachmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOutboxAttachmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOutboxAttachmentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostOutboxResultResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r PostOutboxResultResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r PostOutboxResultResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostOutboxResultResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOutboxResultResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostOutboxResultResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutUploadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Upload
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r PutUploadResponse) GetJSON201() *Upload {
	return r.JSON201
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r PutUploadResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r PutUploadResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutUploadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutUploadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutUploadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetBotVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Version
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetBotVersionResponse) GetJSON200() *Version {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetBotVersionResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetBotVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBotVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBotVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostCommandWithBodyWithResponse A chat command (link, unlink, help, ...)
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /bot/v1/commands (the `PostCommand` operationId).
func (c *ClientWithResponses) PostCommandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCommandResponse, error) {
	rsp, err := c.PostCommandWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCommandResponse(rsp)
}

// PostCommandWithResponse A chat command (link, unlink, help, ...)
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /bot/v1/commands (the `PostCommand` operationId).
func (c *ClientWithResponses) PostCommandWithResponse(ctx context.Context, body PostCommandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCommandResponse, error) {
	rsp, err := c.PostCommand(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCommandResponse(rsp)
}

// GetConversationCursorWithResponse The platform time of the newest message Core holds for a conversation
//
// Lets a bot that lost its own position resume after the right message instead of replaying everything.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /bot/v1/conversations/{id}/cursor (the `GetConversationCursor` operationId).
func (c *ClientWithResponses) GetConversationCursorWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetConversationCursorResponse, error) {
	rsp, err := c.GetConversationCursor(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConversationCursorResponse(rsp)
}

// PostEventWithBodyWithResponse A normalised chat event (created, edited or deleted message)
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /bot/v1/events (the `PostEvent` operationId).
func (c *ClientWithResponses) PostEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEventResponse, error) {
	rsp, err := c.PostEventWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEventResponse(rsp)
}

// PostEventWithResponse A normalised chat event (created, edited or deleted message)
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /bot/v1/events (the `PostEvent` operationId).
func (c *ClientWithResponses) PostEventWithResponse(ctx context.Context, body PostEventJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEventResponse, error) {
	rsp, err := c.PostEvent(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEventResponse(rsp)
}

// PostHeartbeatWithResponse Liveness signal for the admin's bot status
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /bot/v1/heartbeat (the `PostHeartbeat` operationId).
func (c *ClientWithResponses) PostHeartbeatWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostHeartbeatResponse, error) {
	rsp, err := c.PostHeartbeat(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHeartbeatResponse(rsp)
}

// GetIdentityWithResponse Whether a chat identity is linked (nothing about the user)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /bot/v1/identities/{external_user_id} (the `GetIdentity` operationId).
func (c *ClientWithResponses) GetIdentityWithResponse(ctx context.Context, externalUserId string, reqEditors ...RequestEditorFn) (*GetIdentityResponse, error) {
	rsp, err := c.GetIdentity(ctx, externalUserId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIdentityResponse(rsp)
}

// ClaimOutboxWithResponse Long-poll the outbox for items addressed to this bot instance
//
// Claims queued items with a 60-second lease. Waits up to `wait` seconds when nothing is
// available. An item that is not acknowledged before its lease expires is offered again;
// an expired lease does not count as a delivery attempt.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /bot/v1/outbox (the `ClaimOutbox` operationId).
func (c *ClientWithResponses) ClaimOutboxWithResponse(ctx context.Context, params *ClaimOutboxParams, reqEditors ...RequestEditorFn) (*ClaimOutboxResponse, error) {
	rsp, err := c.ClaimOutbox(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClaimOutboxResponse(rsp)
}

// GetOutboxAttachmentWithResponse Download a file that a claimed reminder lists, to send it into the chat
//
// Only files listed in the payload of an item this bot instance has claimed, and only while
// the claim lasts. A bot key never reads anything else of a user's files (BOT-15, SEC-BOT-3).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /bot/v1/outbox/{id}/attachments/{attachmentId} (the `GetOutboxAttachment` operationId).
func (c *ClientWithResponses) GetOutboxAttachmentWithResponse(ctx context.Context, id openapi_types.UUID, attachmentId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetOutboxAttachmentResponse, error) {
	rsp, err := c.GetOutboxAttachment(ctx, id, attachmentId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOutboxAttachmentResponse(rsp)
}

// PostOutboxResultWithBodyWithResponse Report what happened to a claimed outbox item
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /bot/v1/outbox/{id}/result (the `PostOutboxResult` operationId).
func (c *ClientWithResponses) PostOutboxResultWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOutboxResultResponse, error) {
	rsp, err := c.PostOutboxResultWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOutboxResultResponse(rsp)
}

// PostOutboxResultWithResponse Report what happened to a claimed outbox item
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /bot/v1/outbox/{id}/result (the `PostOutboxResult` operationId).
func (c *ClientWithResponses) PostOutboxResultWithResponse(ctx context.Context, id openapi_types.UUID, body PostOutboxResultJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOutboxResultResponse, error) {
	rsp, err := c.PostOutboxResult(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOutboxResultResponse(rsp)
}

// PutUploadWithBodyWithResponse Stream an attachment for a linked chat identity (already decrypted by the bot)
//
// Same storage path and quota as the user upload. The body is the raw file with
// `Content-Type: application/octet-stream` and a required `Content-Length`. The attachment
// stays unlinked until an event references it by `upload_id`; unused ones are removed after an hour.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /bot/v1/uploads/{id} (the `PutUpload` operationId).
func (c *ClientWithResponses) PutUploadWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, params *PutUploadParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutUploadResponse, error) {
	rsp, err := c.PutUploadWithBody(ctx, id, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutUploadResponse(rsp)
}

// GetBotVersionWithResponse Build information
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /bot/v1/version (the `GetBotVersion` operationId).
func (c *ClientWithResponses) GetBotVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBotVersionResponse, error) {
	rsp, err := c.GetBotVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBotVersionResponse(rsp)
}

// ParsePostCommandResponse parses an HTTP response from a PostCommandWithResponse call
func ParsePostCommandResponse(rsp *http.Response) (*PostCommandResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCommandResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommandResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetConversationCursorResponse parses an HTTP response from a GetConversationCursorWithResponse call
func ParseGetConversationCursorResponse(rsp *http.Response) (*GetConversationCursorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConversationCursorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			LastMessageAt *time.Time `json:"last_message_at,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostEventResponse parses an HTTP response from a PostEventWithResponse call
func ParsePostEventResponse(rsp *http.Response) (*PostEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostHeartbeatResponse parses an HTTP response from a PostHeartbeatWithResponse call
func ParsePostHeartbeatResponse(rsp *http.Response) (*PostHeartbeatResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHeartbeatResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetIdentityResponse parses an HTTP response from a GetIdentityWithResponse call
func ParseGetIdentityResponse(rsp *http.Response) (*GetIdentityResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIdentityResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IdentityStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseClaimOutboxResponse parses an HTTP response from a ClaimOutboxWithResponse call
func ParseClaimOutboxResponse(rsp *http.Response) (*ClaimOutboxResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ClaimOutboxResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items []OutboxItem `json:"items"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetOutboxAttachmentResponse parses an HTTP response from a GetOutboxAttachmentWithResponse call
func ParseGetOutboxAttachmentResponse(rsp *http.Response) (*GetOutboxAttachmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOutboxAttachmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostOutboxResultResponse parses an HTTP response from a PostOutboxResultWithResponse call
func ParsePostOutboxResultResponse(rsp *http.Response) (*PostOutboxResultResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOutboxResultResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePutUploadResponse parses an HTTP response from a PutUploadWithResponse call
func ParsePutUploadResponse(rsp *http.Response) (*PutUploadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutUploadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Upload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetBotVersionResponse parses an HTTP response from a GetBotVersionWithResponse call
func ParseGetBotVersionResponse(rsp *http.Response) (*GetBotVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBotVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Version
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
