// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachmentInUse = `-- name: AttachmentInUse :one
select exists(select 1 from note_parts where attachment_id = $1 and user_id = $2)
`

type AttachmentInUseParams struct {
	AttachmentID uuid.NullUUID
	UserID       uuid.UUID
}

func (q *Queries) AttachmentInUse(ctx context.Context, arg AttachmentInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, attachmentInUse, arg.AttachmentID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const attachmentsOfNote = `-- name: AttachmentsOfNote :many
select a.id, a.blob_id, b.size_bytes from note_parts p
join attachments a on a.user_id = p.user_id and a.id = p.attachment_id
join blobs b on b.user_id = a.user_id and b.id = a.blob_id
where p.note_id = $1
`

type AttachmentsOfNoteRow struct {
	ID        uuid.UUID
	BlobID    uuid.UUID
	SizeBytes int64
}

func (q *Queries) AttachmentsOfNote(ctx context.Context, noteID uuid.UUID) ([]AttachmentsOfNoteRow, error) {
	rows, err := q.db.Query(ctx, attachmentsOfNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttachmentsOfNoteRow{}
	for rows.Next() {
		var i AttachmentsOfNoteRow
		if err := rows.Scan(&i.ID, &i.BlobID, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const blobIsShared = `-- name: BlobIsShared :one
select exists(select 1 from attachments where blob_id = $1 and user_id = $2)
`

type BlobIsSharedParams struct {
	BlobID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) BlobIsShared(ctx context.Context, arg BlobIsSharedParams) (bool, error) {
	row := q.db.QueryRow(ctx, blobIsShared, arg.BlobID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const commitReservation = `-- name: CommitReservation :exec
update user_storage set reserved_bytes = greatest(reserved_bytes - $1::bigint, 0), used_bytes = used_bytes + $2::bigint
where user_id = $3
`

type CommitReservationParams struct {
	N      int64
	Stored int64
	UserID uuid.UUID
}

func (q *Queries) CommitReservation(ctx context.Context, arg CommitReservationParams) error {
	_, err := q.db.Exec(ctx, commitReservation, arg.N, arg.Stored, arg.UserID)
	return err
}

const completeBlob = `-- name: CompleteBlob :exec
update blobs set complete = true, size_bytes = $3, sha256 = $4, reserved_bytes = 0, upload_id = null where id = $1 and user_id = $2
`

type CompleteBlobParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	SizeBytes int64
	Sha256    []byte
}

func (q *Queries) CompleteBlob(ctx context.Context, arg CompleteBlobParams) error {
	_, err := q.db.Exec(ctx, completeBlob,
		arg.ID,
		arg.UserID,
		arg.SizeBytes,
		arg.Sha256,
	)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
delete from attachments where id = $1 and user_id = $2
`

type DeleteAttachmentParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteAttachment, arg.ID, arg.UserID)
	return err
}

const deleteBlob = `-- name: DeleteBlob :execrows
delete from blobs where id = $1 and user_id = $2
`

type DeleteBlobParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteBlob(ctx context.Context, arg DeleteBlobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlob, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureStorageRow = `-- name: EnsureStorageRow :exec
insert into user_storage (user_id) values ($1) on conflict do nothing
`

func (q *Queries) EnsureStorageRow(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureStorageRow, userID)
	return err
}

const findDuplicateBlob = `-- name: FindDuplicateBlob :one
select id from blobs where user_id = $1 and sha256 = $2 and size_bytes = $3 and complete and id <> $4 limit 1
`

type FindDuplicateBlobParams struct {
	UserID    uuid.UUID
	Sha256    []byte
	SizeBytes int64
	ID        uuid.UUID
}

func (q *Queries) FindDuplicateBlob(ctx context.Context, arg FindDuplicateBlobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findDuplicateBlob,
		arg.UserID,
		arg.Sha256,
		arg.SizeBytes,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAttachment = `-- name: GetAttachment :one
select id, user_id, blob_id, filename, media_type, created_at from attachments where id = $1 and user_id = $2
`

type GetAttachmentParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.ID, arg.UserID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BlobID,
		&i.Filename,
		&i.MediaType,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentWithBlob = `-- name: GetAttachmentWithBlob :one
select a.id, a.filename, a.media_type, a.created_at, b.id as blob_id, b.size_bytes, b.sha256, b.chunk_size
from attachments a join blobs b on b.user_id = a.user_id and b.id = a.blob_id
where a.id = $1 and a.user_id = $2 and b.complete
`

type GetAttachmentWithBlobParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetAttachmentWithBlobRow struct {
	ID        uuid.UUID
	Filename  string
	MediaType string
	CreatedAt time.Time
	BlobID    uuid.UUID
	SizeBytes int64
	Sha256    []byte
	ChunkSize int32
}

func (q *Queries) GetAttachmentWithBlob(ctx context.Context, arg GetAttachmentWithBlobParams) (GetAttachmentWithBlobRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentWithBlob, arg.ID, arg.UserID)
	var i GetAttachmentWithBlobRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MediaType,
		&i.CreatedAt,
		&i.BlobID,
		&i.SizeBytes,
		&i.Sha256,
		&i.ChunkSize,
	)
	return i, err
}

const getBlob = `-- name: GetBlob :one
select id, user_id, backend, size_bytes, chunk_size, sha256, complete, reserved_bytes, created_at, upload_id from blobs where id = $1 and user_id = $2
`

type GetBlobParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetBlob(ctx context.Context, arg GetBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, getBlob, arg.ID, arg.UserID)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Backend,
		&i.SizeBytes,
		&i.ChunkSize,
		&i.Sha256,
		&i.Complete,
		&i.ReservedBytes,
		&i.CreatedAt,
		&i.UploadID,
	)
	return i, err
}

const getChunk = `-- name: GetChunk :one
select data from blob_chunks where blob_id = $1 and idx = $2
`

type GetChunkParams struct {
	BlobID uuid.UUID
	Idx    int32
}

func (q *Queries) GetChunk(ctx context.Context, arg GetChunkParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getChunk, arg.BlobID, arg.Idx)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const insertAttachment = `-- name: InsertAttachment :one
insert into attachments (id, user_id, blob_id, filename, media_type) values ($1, $2, $3, $4, $5) returning id, user_id, blob_id, filename, media_type, created_at
`

type InsertAttachmentParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	BlobID    uuid.UUID
	Filename  string
	MediaType string
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.ID,
		arg.UserID,
		arg.BlobID,
		arg.Filename,
		arg.MediaType,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BlobID,
		&i.Filename,
		&i.MediaType,
		&i.CreatedAt,
	)
	return i, err
}

const insertBlob = `-- name: InsertBlob :exec
insert into blobs (id, user_id, size_bytes, chunk_size, reserved_bytes, upload_id) values ($1, $2, $3, $4, $3, $5)
`

type InsertBlobParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	SizeBytes int64
	ChunkSize int32
	UploadID  uuid.NullUUID
}

func (q *Queries) InsertBlob(ctx context.Context, arg InsertBlobParams) error {
	_, err := q.db.Exec(ctx, insertBlob,
		arg.ID,
		arg.UserID,
		arg.SizeBytes,
		arg.ChunkSize,
		arg.UploadID,
	)
	return err
}

const insertChunk = `-- name: InsertChunk :exec
insert into blob_chunks (user_id, blob_id, idx, data) values ($1, $2, $3, $4)
`

type InsertChunkParams struct {
	UserID uuid.UUID
	BlobID uuid.UUID
	Idx    int32
	Data   []byte
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.db.Exec(ctx, insertChunk,
		arg.UserID,
		arg.BlobID,
		arg.Idx,
		arg.Data,
	)
	return err
}

const partAttachmentInfo = `-- name: PartAttachmentInfo :many
select a.id, a.filename, a.media_type, b.size_bytes from attachments a join blobs b on b.user_id = a.user_id and b.id = a.blob_id
where a.id = any($1::uuid[]) and a.user_id = $2
`

type PartAttachmentInfoParams struct {
	Column1 []uuid.UUID
	UserID  uuid.UUID
}

type PartAttachmentInfoRow struct {
	ID        uuid.UUID
	Filename  string
	MediaType string
	SizeBytes int64
}

func (q *Queries) PartAttachmentInfo(ctx context.Context, arg PartAttachmentInfoParams) ([]PartAttachmentInfoRow, error) {
	rows, err := q.db.Query(ctx, partAttachmentInfo, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PartAttachmentInfoRow{}
	for rows.Next() {
		var i PartAttachmentInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.MediaType,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseReservation = `-- name: ReleaseReservation :exec
update user_storage set reserved_bytes = greatest(reserved_bytes - $1::bigint, 0) where user_id = $2
`

type ReleaseReservationParams struct {
	N      int64
	UserID uuid.UUID
}

func (q *Queries) ReleaseReservation(ctx context.Context, arg ReleaseReservationParams) error {
	_, err := q.db.Exec(ctx, releaseReservation, arg.N, arg.UserID)
	return err
}

const releaseUsed = `-- name: ReleaseUsed :exec
update user_storage set used_bytes = greatest(used_bytes - $1::bigint, 0) where user_id = $2
`

type ReleaseUsedParams struct {
	N      int64
	UserID uuid.UUID
}

func (q *Queries) ReleaseUsed(ctx context.Context, arg ReleaseUsedParams) error {
	_, err := q.db.Exec(ctx, releaseUsed, arg.N, arg.UserID)
	return err
}

const reserveQuota = `-- name: ReserveQuota :execrows
update user_storage set reserved_bytes = reserved_bytes + $1::bigint
where user_id = $2 and used_bytes + reserved_bytes + $1::bigint <= coalesce(quota_bytes, $3::bigint)
`

type ReserveQuotaParams struct {
	N            int64
	UserID       uuid.UUID
	DefaultQuota int64
}

func (q *Queries) ReserveQuota(ctx context.Context, arg ReserveQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveQuota, arg.N, arg.UserID, arg.DefaultQuota)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const staleIncompleteBlobs = `-- name: StaleIncompleteBlobs :many
select id, reserved_bytes from blobs where user_id = $1 and not complete and created_at < $2
`

type StaleIncompleteBlobsParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

type StaleIncompleteBlobsRow struct {
	ID            uuid.UUID
	ReservedBytes int64
}

func (q *Queries) StaleIncompleteBlobs(ctx context.Context, arg StaleIncompleteBlobsParams) ([]StaleIncompleteBlobsRow, error) {
	rows, err := q.db.Query(ctx, staleIncompleteBlobs, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaleIncompleteBlobsRow{}
	for rows.Next() {
		var i StaleIncompleteBlobsRow
		if err := rows.Scan(&i.ID, &i.ReservedBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storageUsage = `-- name: StorageUsage :one
select used_bytes, reserved_bytes, quota_bytes from user_storage where user_id = $1
`

type StorageUsageRow struct {
	UsedBytes     int64
	ReservedBytes int64
	QuotaBytes    *int64
}

func (q *Queries) StorageUsage(ctx context.Context, userID uuid.UUID) (StorageUsageRow, error) {
	row := q.db.QueryRow(ctx, storageUsage, userID)
	var i StorageUsageRow
	err := row.Scan(&i.UsedBytes, &i.ReservedBytes, &i.QuotaBytes)
	return i, err
}

const unlinkedAttachments = `-- name: UnlinkedAttachments :many
select a.id from attachments a
where a.user_id = $1 and a.created_at < $2
  and not exists (select 1 from note_parts p where p.attachment_id = a.id)
`

type UnlinkedAttachmentsParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) UnlinkedAttachments(ctx context.Context, arg UnlinkedAttachmentsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, unlinkedAttachments, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uploadInProgress = `-- name: UploadInProgress :one
select exists(select 1 from blobs where user_id = $1 and upload_id = $2 and not complete)
`

type UploadInProgressParams struct {
	UserID   uuid.UUID
	UploadID uuid.NullUUID
}

func (q *Queries) UploadInProgress(ctx context.Context, arg UploadInProgressParams) (bool, error) {
	row := q.db.QueryRow(ctx, uploadInProgress, arg.UserID, arg.UploadID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
