// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const categoryIDsOfPage = `-- name: CategoryIDsOfPage :many
select id from categories where user_id = $1 and page_id = $2
`

type CategoryIDsOfPageParams struct {
	UserID uuid.UUID
	PageID uuid.UUID
}

func (q *Queries) CategoryIDsOfPage(ctx context.Context, arg CategoryIDsOfPageParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, categoryIDsOfPage, arg.UserID, arg.PageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryIDsOrdered = `-- name: CategoryIDsOrdered :many
select id from categories where user_id = $1 and page_id = $2 and id <> $3 order by position, id
`

type CategoryIDsOrderedParams struct {
	UserID uuid.UUID
	PageID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) CategoryIDsOrdered(ctx context.Context, arg CategoryIDsOrderedParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, categoryIDsOrdered, arg.UserID, arg.PageID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryKeyAfter = `-- name: CategoryKeyAfter :one
select position from categories where user_id = $1 and page_id = $2 and id <> $3 and position > $4 order by position, id limit 1
`

type CategoryKeyAfterParams struct {
	UserID   uuid.UUID
	PageID   uuid.UUID
	ID       uuid.UUID
	Position string
}

func (q *Queries) CategoryKeyAfter(ctx context.Context, arg CategoryKeyAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, categoryKeyAfter,
		arg.UserID,
		arg.PageID,
		arg.ID,
		arg.Position,
	)
	var position string
	err := row.Scan(&position)
	return position, err
}

const categoryKeyBefore = `-- name: CategoryKeyBefore :one
select position from categories where user_id = $1 and page_id = $2 and id <> $3 and position < $4 order by position desc, id desc limit 1
`

type CategoryKeyBeforeParams struct {
	UserID   uuid.UUID
	PageID   uuid.UUID
	ID       uuid.UUID
	Position string
}

func (q *Queries) CategoryKeyBefore(ctx context.Context, arg CategoryKeyBeforeParams) (string, error) {
	row := q.db.QueryRow(ctx, categoryKeyBefore,
		arg.UserID,
		arg.PageID,
		arg.ID,
		arg.Position,
	)
	var position string
	err := row.Scan(&position)
	return position, err
}

const categoryKeyFirst = `-- name: CategoryKeyFirst :one
select position from categories where user_id = $1 and page_id = $2 and id <> $3 order by position, id limit 1
`

type CategoryKeyFirstParams struct {
	UserID uuid.UUID
	PageID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) CategoryKeyFirst(ctx context.Context, arg CategoryKeyFirstParams) (string, error) {
	row := q.db.QueryRow(ctx, categoryKeyFirst, arg.UserID, arg.PageID, arg.ID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const categoryKeyLast = `-- name: CategoryKeyLast :one
select position from categories where user_id = $1 and page_id = $2 and id <> $3 order by position desc, id desc limit 1
`

type CategoryKeyLastParams struct {
	UserID uuid.UUID
	PageID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) CategoryKeyLast(ctx context.Context, arg CategoryKeyLastParams) (string, error) {
	row := q.db.QueryRow(ctx, categoryKeyLast, arg.UserID, arg.PageID, arg.ID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const categoryNotePositions = `-- name: CategoryNotePositions :many
select id from notes where user_id = $1 and category_id = $2 and state = 'active' and id <> $3 order by position, id
`

type CategoryNotePositionsParams struct {
	UserID     uuid.UUID
	CategoryID uuid.NullUUID
	ID         uuid.UUID
}

func (q *Queries) CategoryNotePositions(ctx context.Context, arg CategoryNotePositionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, categoryNotePositions, arg.UserID, arg.CategoryID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCategoryNotes = `-- name: CountCategoryNotes :one
select count(*) from notes where user_id = $1 and category_id = $2 and state = 'active'
`

type CountCategoryNotesParams struct {
	UserID     uuid.UUID
	CategoryID uuid.NullUUID
}

func (q *Queries) CountCategoryNotes(ctx context.Context, arg CountCategoryNotesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryNotes, arg.UserID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
delete from categories where id = $1 and user_id = $2
`

type DeleteCategoryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePage = `-- name: DeletePage :execrows
delete from pages where id = $1 and user_id = $2
`

type DeletePageParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePage(ctx context.Context, arg DeletePageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePage, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
select id, user_id, page_id, name, position, created_at, updated_at, version from categories where id = $1 and user_id = $2
`

type GetCategoryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PageID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getPage = `-- name: GetPage :one
select id, user_id, name, position, archived_at, created_at, updated_at, version from pages where id = $1 and user_id = $2
`

type GetPageParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPage(ctx context.Context, arg GetPageParams) (Page, error) {
	row := q.db.QueryRow(ctx, getPage, arg.ID, arg.UserID)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one

insert into categories (id, user_id, page_id, name, position) values ($1, $2, $3, $4, $5) returning id, user_id, page_id, name, position, created_at, updated_at, version
`

type InsertCategoryParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	PageID   uuid.UUID
	Name     string
	Position string
}

// ---- categories ----
func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertCategory,
		arg.ID,
		arg.UserID,
		arg.PageID,
		arg.Name,
		arg.Position,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PageID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertPage = `-- name: InsertPage :one

insert into pages (id, user_id, name, position) values ($1, $2, $3, $4) returning id, user_id, name, position, archived_at, created_at, updated_at, version
`

type InsertPageParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Name     string
	Position string
}

// ---- pages ----
func (q *Queries) InsertPage(ctx context.Context, arg InsertPageParams) (Page, error) {
	row := q.db.QueryRow(ctx, insertPage,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Position,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listAllCategories = `-- name: ListAllCategories :many
select id, page_id, name from categories where user_id = $1 order by page_id, position, id
`

type ListAllCategoriesRow struct {
	ID     uuid.UUID
	PageID uuid.UUID
	Name   string
}

func (q *Queries) ListAllCategories(ctx context.Context, userID uuid.UUID) ([]ListAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listAllCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCategoriesRow{}
	for rows.Next() {
		var i ListAllCategoriesRow
		if err := rows.Scan(&i.ID, &i.PageID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesOfPage = `-- name: ListCategoriesOfPage :many
select id, user_id, page_id, name, position, created_at, updated_at, version from categories where user_id = $1 and page_id = $2 order by position, id
`

type ListCategoriesOfPageParams struct {
	UserID uuid.UUID
	PageID uuid.UUID
}

func (q *Queries) ListCategoriesOfPage(ctx context.Context, arg ListCategoriesOfPageParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesOfPage, arg.UserID, arg.PageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PageID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryNotes = `-- name: ListCategoryNotes :many

select id, user_id, category_id, position, state, deleted_at, created_at, received_at, updated_at, version from notes
where user_id = $1 and category_id = $2 and state = 'active'
  and ($4::text is null or (position, id) > ($4::text collate "C", $5::uuid))
order by position, id
limit $3
`

type ListCategoryNotesParams struct {
	UserID        uuid.UUID
	CategoryID    uuid.NullUUID
	Limit         int32
	AfterPosition *string
	AfterID       uuid.NullUUID
}

// ---- notes in categories ----
func (q *Queries) ListCategoryNotes(ctx context.Context, arg ListCategoryNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listCategoryNotes,
		arg.UserID,
		arg.CategoryID,
		arg.Limit,
		arg.AfterPosition,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Position,
			&i.State,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.ReceivedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPages = `-- name: ListPages :many
select id, user_id, name, position, archived_at, created_at, updated_at, version from pages where user_id = $1 order by position, id
`

func (q *Queries) ListPages(ctx context.Context, userID uuid.UUID) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Position,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noteIDsInCategories = `-- name: NoteIDsInCategories :many
select id from notes where user_id = $1 and category_id = any($2::uuid[])
`

type NoteIDsInCategoriesParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) NoteIDsInCategories(ctx context.Context, arg NoteIDsInCategoriesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, noteIDsInCategories, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noteKeyAfter = `-- name: NoteKeyAfter :one
select position from notes where user_id = $1 and category_id = $2 and state = 'active' and id <> $3 and position > $4 order by position, id limit 1
`

type NoteKeyAfterParams struct {
	UserID     uuid.UUID
	CategoryID uuid.NullUUID
	ID         uuid.UUID
	Position   *string
}

func (q *Queries) NoteKeyAfter(ctx context.Context, arg NoteKeyAfterParams) (*string, error) {
	row := q.db.QueryRow(ctx, noteKeyAfter,
		arg.UserID,
		arg.CategoryID,
		arg.ID,
		arg.Position,
	)
	var position *string
	err := row.Scan(&position)
	return position, err
}

const noteKeyBefore = `-- name: NoteKeyBefore :one
select position from notes where user_id = $1 and category_id = $2 and state = 'active' and id <> $3 and position < $4 order by position desc, id desc limit 1
`

type NoteKeyBeforeParams struct {
	UserID     uuid.UUID
	CategoryID uuid.NullUUID
	ID         uuid.UUID
	Position   *string
}

func (q *Queries) NoteKeyBefore(ctx context.Context, arg NoteKeyBeforeParams) (*string, error) {
	row := q.db.QueryRow(ctx, noteKeyBefore,
		arg.UserID,
		arg.CategoryID,
		arg.ID,
		arg.Position,
	)
	var position *string
	err := row.Scan(&position)
	return position, err
}

const noteKeyFirst = `-- name: NoteKeyFirst :one
select position from notes where user_id = $1 and category_id = $2 and state = 'active' and id <> $3 order by position, id limit 1
`

type NoteKeyFirstParams struct {
	UserID     uuid.UUID
	CategoryID uuid.NullUUID
	ID         uuid.UUID
}

func (q *Queries) NoteKeyFirst(ctx context.Context, arg NoteKeyFirstParams) (*string, error) {
	row := q.db.QueryRow(ctx, noteKeyFirst, arg.UserID, arg.CategoryID, arg.ID)
	var position *string
	err := row.Scan(&position)
	return position, err
}

const noteKeyLast = `-- name: NoteKeyLast :one
select position from notes where user_id = $1 and category_id = $2 and state = 'active' and id <> $3 order by position desc, id desc limit 1
`

type NoteKeyLastParams struct {
	UserID     uuid.UUID
	CategoryID uuid.NullUUID
	ID         uuid.UUID
}

func (q *Queries) NoteKeyLast(ctx context.Context, arg NoteKeyLastParams) (*string, error) {
	row := q.db.QueryRow(ctx, noteKeyLast, arg.UserID, arg.CategoryID, arg.ID)
	var position *string
	err := row.Scan(&position)
	return position, err
}

const notePosition = `-- name: NotePosition :one
select position from notes where user_id = $1 and id = $2 and category_id = $3 and state = 'active'
`

type NotePositionParams struct {
	UserID     uuid.UUID
	ID         uuid.UUID
	CategoryID uuid.NullUUID
}

func (q *Queries) NotePosition(ctx context.Context, arg NotePositionParams) (*string, error) {
	row := q.db.QueryRow(ctx, notePosition, arg.UserID, arg.ID, arg.CategoryID)
	var position *string
	err := row.Scan(&position)
	return position, err
}

const pageIDsOrdered = `-- name: PageIDsOrdered :many
select id from pages where user_id = $1 and id <> $2 order by position, id
`

type PageIDsOrderedParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) PageIDsOrdered(ctx context.Context, arg PageIDsOrderedParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, pageIDsOrdered, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageKeyAfter = `-- name: PageKeyAfter :one
select position from pages where user_id = $1 and id <> $2 and position > $3 order by position, id limit 1
`

type PageKeyAfterParams struct {
	UserID   uuid.UUID
	ID       uuid.UUID
	Position string
}

func (q *Queries) PageKeyAfter(ctx context.Context, arg PageKeyAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, pageKeyAfter, arg.UserID, arg.ID, arg.Position)
	var position string
	err := row.Scan(&position)
	return position, err
}

const pageKeyBefore = `-- name: PageKeyBefore :one
select position from pages where user_id = $1 and id <> $2 and position < $3 order by position desc, id desc limit 1
`

type PageKeyBeforeParams struct {
	UserID   uuid.UUID
	ID       uuid.UUID
	Position string
}

func (q *Queries) PageKeyBefore(ctx context.Context, arg PageKeyBeforeParams) (string, error) {
	row := q.db.QueryRow(ctx, pageKeyBefore, arg.UserID, arg.ID, arg.Position)
	var position string
	err := row.Scan(&position)
	return position, err
}

const pageKeyFirst = `-- name: PageKeyFirst :one
select position from pages where user_id = $1 and id <> $2 order by position, id limit 1
`

type PageKeyFirstParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) PageKeyFirst(ctx context.Context, arg PageKeyFirstParams) (string, error) {
	row := q.db.QueryRow(ctx, pageKeyFirst, arg.UserID, arg.ID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const pageKeyLast = `-- name: PageKeyLast :one
select position from pages where user_id = $1 and id <> $2 order by position desc, id desc limit 1
`

type PageKeyLastParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) PageKeyLast(ctx context.Context, arg PageKeyLastParams) (string, error) {
	row := q.db.QueryRow(ctx, pageKeyLast, arg.UserID, arg.ID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const rekeyCategory = `-- name: RekeyCategory :one
update categories set position = $3, updated_at = $4, version = version + 1 where id = $1 and user_id = $2 returning version
`

type RekeyCategoryParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Position  string
	UpdatedAt time.Time
}

func (q *Queries) RekeyCategory(ctx context.Context, arg RekeyCategoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, rekeyCategory,
		arg.ID,
		arg.UserID,
		arg.Position,
		arg.UpdatedAt,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const rekeyNote = `-- name: RekeyNote :one
update notes set position = $3, updated_at = $4, version = version + 1 where id = $1 and user_id = $2 returning version
`

type RekeyNoteParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Position  *string
	UpdatedAt time.Time
}

func (q *Queries) RekeyNote(ctx context.Context, arg RekeyNoteParams) (int32, error) {
	row := q.db.QueryRow(ctx, rekeyNote,
		arg.ID,
		arg.UserID,
		arg.Position,
		arg.UpdatedAt,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const rekeyPage = `-- name: RekeyPage :one
update pages set position = $3, updated_at = $4, version = version + 1 where id = $1 and user_id = $2 returning version
`

type RekeyPageParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Position  string
	UpdatedAt time.Time
}

func (q *Queries) RekeyPage(ctx context.Context, arg RekeyPageParams) (int32, error) {
	row := q.db.QueryRow(ctx, rekeyPage,
		arg.ID,
		arg.UserID,
		arg.Position,
		arg.UpdatedAt,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const updateCategory = `-- name: UpdateCategory :one
update categories set name = coalesce($1, name), position = coalesce($2, position),
  page_id = coalesce($3, page_id), updated_at = $4, version = version + 1
where id = $5 and user_id = $6 returning id, user_id, page_id, name, position, created_at, updated_at, version
`

type UpdateCategoryParams struct {
	Name     *string
	Position *string
	PageID   uuid.NullUUID
	Now      time.Time
	ID       uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Position,
		arg.PageID,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PageID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updatePage = `-- name: UpdatePage :one
update pages set name = coalesce($1, name), position = coalesce($2, position),
  archived_at = case when $3::bool is null then archived_at
                     when $3::bool then coalesce(archived_at, $4::timestamptz) else null end,
  updated_at = $4, version = version + 1
where id = $5 and user_id = $6 returning id, user_id, name, position, archived_at, created_at, updated_at, version
`

type UpdatePageParams struct {
	Name     *string
	Position *string
	Archived pgtype.Bool
	Now      time.Time
	ID       uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.Name,
		arg.Position,
		arg.Archived,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
