// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePairingCode = `-- name: ConsumePairingCode :one
update pairing_codes set used_at = $2
where id = $1 and used_at is null and expires_at > $2
returning user_id
`

type ConsumePairingCodeParams struct {
	ID     uuid.UUID
	UsedAt *time.Time
}

func (q *Queries) ConsumePairingCode(ctx context.Context, arg ConsumePairingCodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumePairingCode, arg.ID, arg.UsedAt)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const countActivePairingCodes = `-- name: CountActivePairingCodes :one
select count(*) from pairing_codes where user_id = $1 and used_at is null and expires_at > $2
`

type CountActivePairingCodesParams struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CountActivePairingCodes(ctx context.Context, arg CountActivePairingCodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePairingCodes, arg.UserID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserIdentities = `-- name: CountUserIdentities :one
select count(*) from external_identities where user_id = $1
`

func (q *Queries) CountUserIdentities(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserIdentities, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBotCredential = `-- name: CreateBotCredential :one
insert into bot_credentials (id, bot_instance_id, client_id, secret_hash, scopes)
values ($1, $2, $3, $4, $5) returning id, bot_instance_id, client_id, secret_hash, scopes, created_at, disabled_at
`

type CreateBotCredentialParams struct {
	ID            uuid.UUID
	BotInstanceID uuid.UUID
	ClientID      string
	SecretHash    []byte
	Scopes        []string
}

func (q *Queries) CreateBotCredential(ctx context.Context, arg CreateBotCredentialParams) (BotCredential, error) {
	row := q.db.QueryRow(ctx, createBotCredential,
		arg.ID,
		arg.BotInstanceID,
		arg.ClientID,
		arg.SecretHash,
		arg.Scopes,
	)
	var i BotCredential
	err := row.Scan(
		&i.ID,
		&i.BotInstanceID,
		&i.ClientID,
		&i.SecretHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const createBotInstance = `-- name: CreateBotInstance :one
insert into bot_instances (id, type, name, identity_domain) values ($1, $2, $3, $4) returning id, type, name, identity_domain, status, last_seen_at, created_at
`

type CreateBotInstanceParams struct {
	ID             uuid.UUID
	Type           string
	Name           string
	IdentityDomain string
}

func (q *Queries) CreateBotInstance(ctx context.Context, arg CreateBotInstanceParams) (BotInstance, error) {
	row := q.db.QueryRow(ctx, createBotInstance,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.IdentityDomain,
	)
	var i BotInstance
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.IdentityDomain,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIdentity = `-- name: DeleteIdentity :execrows
delete from external_identities where id = $1 and user_id = $2
`

type DeleteIdentityParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentity, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableBotCredential = `-- name: DisableBotCredential :execrows
update bot_credentials set disabled_at = $3 where id = $1 and bot_instance_id = $2 and disabled_at is null
`

type DisableBotCredentialParams struct {
	ID            uuid.UUID
	BotInstanceID uuid.UUID
	DisabledAt    *time.Time
}

func (q *Queries) DisableBotCredential(ctx context.Context, arg DisableBotCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableBotCredential, arg.ID, arg.BotInstanceID, arg.DisabledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBotCredentialByClientID = `-- name: GetBotCredentialByClientID :one
select c.id as credential_id, c.secret_hash, c.scopes, c.disabled_at,
       i.id as instance_id, i.type, i.name, i.identity_domain, i.status
from bot_credentials c join bot_instances i on i.id = c.bot_instance_id
where c.client_id = $1
`

type GetBotCredentialByClientIDRow struct {
	CredentialID   uuid.UUID
	SecretHash     []byte
	Scopes         []string
	DisabledAt     *time.Time
	InstanceID     uuid.UUID
	Type           string
	Name           string
	IdentityDomain string
	Status         string
}

func (q *Queries) GetBotCredentialByClientID(ctx context.Context, clientID string) (GetBotCredentialByClientIDRow, error) {
	row := q.db.QueryRow(ctx, getBotCredentialByClientID, clientID)
	var i GetBotCredentialByClientIDRow
	err := row.Scan(
		&i.CredentialID,
		&i.SecretHash,
		&i.Scopes,
		&i.DisabledAt,
		&i.InstanceID,
		&i.Type,
		&i.Name,
		&i.IdentityDomain,
		&i.Status,
	)
	return i, err
}

const getBotInstance = `-- name: GetBotInstance :one
select id, type, name, identity_domain, status, last_seen_at, created_at from bot_instances where id = $1
`

func (q *Queries) GetBotInstance(ctx context.Context, id uuid.UUID) (BotInstance, error) {
	row := q.db.QueryRow(ctx, getBotInstance, id)
	var i BotInstance
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.IdentityDomain,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentity = `-- name: GetIdentity :one
select id, user_id, bot_instance_id, bot_type, external_user_id, conversation_id, reminder_target, linked_at from external_identities where id = $1
`

func (q *Queries) GetIdentity(ctx context.Context, id uuid.UUID) (ExternalIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentity, id)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BotInstanceID,
		&i.BotType,
		&i.ExternalUserID,
		&i.ConversationID,
		&i.ReminderTarget,
		&i.LinkedAt,
	)
	return i, err
}

const getIdentityByExternal = `-- name: GetIdentityByExternal :one
select id, user_id, bot_instance_id, bot_type, external_user_id, conversation_id, reminder_target, linked_at from external_identities where bot_type = $1 and external_user_id = $2
`

type GetIdentityByExternalParams struct {
	BotType        string
	ExternalUserID string
}

func (q *Queries) GetIdentityByExternal(ctx context.Context, arg GetIdentityByExternalParams) (ExternalIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByExternal, arg.BotType, arg.ExternalUserID)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BotInstanceID,
		&i.BotType,
		&i.ExternalUserID,
		&i.ConversationID,
		&i.ReminderTarget,
		&i.LinkedAt,
	)
	return i, err
}

const insertIdentity = `-- name: InsertIdentity :one
insert into external_identities (id, user_id, bot_instance_id, bot_type, external_user_id, conversation_id, reminder_target, linked_at)
values ($1, $2, $3, $4, $5, $6, $7, $8) returning id, user_id, bot_instance_id, bot_type, external_user_id, conversation_id, reminder_target, linked_at
`

type InsertIdentityParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	BotInstanceID  uuid.UUID
	BotType        string
	ExternalUserID string
	ConversationID *string
	ReminderTarget bool
	LinkedAt       time.Time
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) (ExternalIdentity, error) {
	row := q.db.QueryRow(ctx, insertIdentity,
		arg.ID,
		arg.UserID,
		arg.BotInstanceID,
		arg.BotType,
		arg.ExternalUserID,
		arg.ConversationID,
		arg.ReminderTarget,
		arg.LinkedAt,
	)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BotInstanceID,
		&i.BotType,
		&i.ExternalUserID,
		&i.ConversationID,
		&i.ReminderTarget,
		&i.LinkedAt,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
insert into bot_outbox (id, bot_instance_id, kind, user_id, external_user_id, conversation_id, payload, next_attempt_at)
values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertOutboxParams struct {
	ID             uuid.UUID
	BotInstanceID  uuid.UUID
	Kind           string
	UserID         uuid.NullUUID
	ExternalUserID string
	ConversationID string
	Payload        []byte
	NextAttemptAt  time.Time
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.ID,
		arg.BotInstanceID,
		arg.Kind,
		arg.UserID,
		arg.ExternalUserID,
		arg.ConversationID,
		arg.Payload,
		arg.NextAttemptAt,
	)
	return err
}

const insertPairingCode = `-- name: InsertPairingCode :exec
insert into pairing_codes (id, user_id, code_hash, bot_instance_id, bot_type, expires_at)
values ($1, $2, $3, $4, $5, $6)
`

type InsertPairingCodeParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	CodeHash      []byte
	BotInstanceID uuid.NullUUID
	BotType       string
	ExpiresAt     time.Time
}

func (q *Queries) InsertPairingCode(ctx context.Context, arg InsertPairingCodeParams) error {
	_, err := q.db.Exec(ctx, insertPairingCode,
		arg.ID,
		arg.UserID,
		arg.CodeHash,
		arg.BotInstanceID,
		arg.BotType,
		arg.ExpiresAt,
	)
	return err
}

const listBotCredentials = `-- name: ListBotCredentials :many
select id, client_id, scopes, created_at, disabled_at from bot_credentials
where bot_instance_id = $1 order by created_at
`

type ListBotCredentialsRow struct {
	ID         uuid.UUID
	ClientID   string
	Scopes     []string
	CreatedAt  time.Time
	DisabledAt *time.Time
}

func (q *Queries) ListBotCredentials(ctx context.Context, botInstanceID uuid.UUID) ([]ListBotCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listBotCredentials, botInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBotCredentialsRow{}
	for rows.Next() {
		var i ListBotCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Scopes,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotInstances = `-- name: ListBotInstances :many
select id, type, name, identity_domain, status, last_seen_at, created_at from bot_instances order by name
`

func (q *Queries) ListBotInstances(ctx context.Context) ([]BotInstance, error) {
	rows, err := q.db.Query(ctx, listBotInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotInstance{}
	for rows.Next() {
		var i BotInstance
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.IdentityDomain,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIdentities = `-- name: ListUserIdentities :many
select e.id, e.bot_instance_id, i.name as instance_name, e.bot_type, e.external_user_id,
       e.conversation_id, e.reminder_target, e.linked_at
from external_identities e join bot_instances i on i.id = e.bot_instance_id
where e.user_id = $1 order by e.linked_at
`

type ListUserIdentitiesRow struct {
	ID             uuid.UUID
	BotInstanceID  uuid.UUID
	InstanceName   string
	BotType        string
	ExternalUserID string
	ConversationID *string
	ReminderTarget bool
	LinkedAt       time.Time
}

func (q *Queries) ListUserIdentities(ctx context.Context, userID uuid.UUID) ([]ListUserIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listUserIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserIdentitiesRow{}
	for rows.Next() {
		var i ListUserIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.BotInstanceID,
			&i.InstanceName,
			&i.BotType,
			&i.ExternalUserID,
			&i.ConversationID,
			&i.ReminderTarget,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPairingCode = `-- name: LookupPairingCode :one
select id, user_id, bot_instance_id, bot_type from pairing_codes
where code_hash = $1 and used_at is null and expires_at > $2
`

type LookupPairingCodeParams struct {
	CodeHash  []byte
	ExpiresAt time.Time
}

type LookupPairingCodeRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	BotInstanceID uuid.NullUUID
	BotType       string
}

func (q *Queries) LookupPairingCode(ctx context.Context, arg LookupPairingCodeParams) (LookupPairingCodeRow, error) {
	row := q.db.QueryRow(ctx, lookupPairingCode, arg.CodeHash, arg.ExpiresAt)
	var i LookupPairingCodeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BotInstanceID,
		&i.BotType,
	)
	return i, err
}

const noticeDue = `-- name: NoticeDue :one
insert into unlinked_senders (bot_instance_id, external_user_id, last_notice_at)
values ($1, $2, $3)
on conflict (bot_instance_id, external_user_id) do update set last_notice_at = $3
  where unlinked_senders.last_notice_at < $4
returning true
`

type NoticeDueParams struct {
	BotInstanceID  uuid.UUID
	ExternalUserID string
	LastNoticeAt   time.Time
	LastNoticeAt_2 time.Time
}

func (q *Queries) NoticeDue(ctx context.Context, arg NoticeDueParams) (bool, error) {
	row := q.db.QueryRow(ctx, noticeDue,
		arg.BotInstanceID,
		arg.ExternalUserID,
		arg.LastNoticeAt,
		arg.LastNoticeAt_2,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setBotInstanceStatus = `-- name: SetBotInstanceStatus :execrows
update bot_instances set status = $2 where id = $1
`

type SetBotInstanceStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetBotInstanceStatus(ctx context.Context, arg SetBotInstanceStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBotInstanceStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setReminderTarget = `-- name: SetReminderTarget :execrows
update external_identities set reminder_target = $3 where id = $1 and user_id = $2
`

type SetReminderTargetParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ReminderTarget bool
}

func (q *Queries) SetReminderTarget(ctx context.Context, arg SetReminderTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReminderTarget, arg.ID, arg.UserID, arg.ReminderTarget)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchBotInstance = `-- name: TouchBotInstance :exec
update bot_instances set last_seen_at = $2 where id = $1
`

type TouchBotInstanceParams struct {
	ID         uuid.UUID
	LastSeenAt *time.Time
}

func (q *Queries) TouchBotInstance(ctx context.Context, arg TouchBotInstanceParams) error {
	_, err := q.db.Exec(ctx, touchBotInstance, arg.ID, arg.LastSeenAt)
	return err
}

const updateIdentityConversation = `-- name: UpdateIdentityConversation :exec
update external_identities set conversation_id = $2 where id = $1 and conversation_id is distinct from $2
`

type UpdateIdentityConversationParams struct {
	ID             uuid.UUID
	ConversationID *string
}

func (q *Queries) UpdateIdentityConversation(ctx context.Context, arg UpdateIdentityConversationParams) error {
	_, err := q.db.Exec(ctx, updateIdentityConversation, arg.ID, arg.ConversationID)
	return err
}
