// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRecentExports = `-- name: CountRecentExports :one
select count(*) from audit_log where action = 'user.exported' and target_id = $1 and at > $2
`

type CountRecentExportsParams struct {
	TargetID uuid.NullUUID
	At       time.Time
}

func (q *Queries) CountRecentExports(ctx context.Context, arg CountRecentExportsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentExports, arg.TargetID, arg.At)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const exportAttachmentInfo = `-- name: ExportAttachmentInfo :many
select a.id, a.filename, a.media_type, b.size_bytes from attachments a join blobs b on b.user_id = a.user_id and b.id = a.blob_id
where a.user_id = $1 and a.id = any($2::uuid[])
`

type ExportAttachmentInfoParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

type ExportAttachmentInfoRow struct {
	ID        uuid.UUID
	Filename  string
	MediaType string
	SizeBytes int64
}

func (q *Queries) ExportAttachmentInfo(ctx context.Context, arg ExportAttachmentInfoParams) ([]ExportAttachmentInfoRow, error) {
	rows, err := q.db.Query(ctx, exportAttachmentInfo, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportAttachmentInfoRow{}
	for rows.Next() {
		var i ExportAttachmentInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.MediaType,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCategories = `-- name: ExportCategories :many
select id, user_id, page_id, name, position, created_at, updated_at, version from categories where user_id = $1 order by page_id, position, id
`

func (q *Queries) ExportCategories(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, exportCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PageID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportNotes = `-- name: ExportNotes :many
select id, user_id, category_id, position, state, deleted_at, created_at, received_at, updated_at, version from notes where user_id = $1 and id > $2 order by id limit $3
`

type ExportNotesParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Limit  int32
}

func (q *Queries) ExportNotes(ctx context.Context, arg ExportNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, exportNotes, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Position,
			&i.State,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.ReceivedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportPages = `-- name: ExportPages :many
select id, user_id, name, position, archived_at, created_at, updated_at, version from pages where user_id = $1 order by position, id
`

func (q *Queries) ExportPages(ctx context.Context, userID uuid.UUID) ([]Page, error) {
	rows, err := q.db.Query(ctx, exportPages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Position,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportParts = `-- name: ExportParts :many
select id, user_id, note_id, ordinal, kind, text, attachment_id, failed_filename, failed_size, failed_reason, attach_reason, related_part_id, created_at, text_edited_at, source_bot_instance_id, source_identity_id, source_conversation_id, source_message_id, source_part_index from note_parts where user_id = $1 and note_id = any($2::uuid[]) order by note_id, ordinal
`

type ExportPartsParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

func (q *Queries) ExportParts(ctx context.Context, arg ExportPartsParams) ([]NotePart, error) {
	rows, err := q.db.Query(ctx, exportParts, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotePart{}
	for rows.Next() {
		var i NotePart
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteID,
			&i.Ordinal,
			&i.Kind,
			&i.Text,
			&i.AttachmentID,
			&i.FailedFilename,
			&i.FailedSize,
			&i.FailedReason,
			&i.AttachReason,
			&i.RelatedPartID,
			&i.CreatedAt,
			&i.TextEditedAt,
			&i.SourceBotInstanceID,
			&i.SourceIdentityID,
			&i.SourceConversationID,
			&i.SourceMessageID,
			&i.SourcePartIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportReminders = `-- name: ExportReminders :many
select id, user_id, note_id, due_at, rrule, tz, state, last_fired_at, claimed_until, created_at, version from reminders where user_id = $1 order by note_id, due_at, id
`

func (q *Queries) ExportReminders(ctx context.Context, userID uuid.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, exportReminders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteID,
			&i.DueAt,
			&i.Rrule,
			&i.Tz,
			&i.State,
			&i.LastFiredAt,
			&i.ClaimedUntil,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportShareLinks = `-- name: ExportShareLinks :many
select id, note_id, created_at, expires_at, revoked_at, last_accessed_at, view_count from share_links where user_id = $1 order by created_at, id
`

type ExportShareLinksRow struct {
	ID             uuid.UUID
	NoteID         uuid.UUID
	CreatedAt      time.Time
	ExpiresAt      time.Time
	RevokedAt      *time.Time
	LastAccessedAt *time.Time
	ViewCount      int32
}

func (q *Queries) ExportShareLinks(ctx context.Context, userID uuid.UUID) ([]ExportShareLinksRow, error) {
	rows, err := q.db.Query(ctx, exportShareLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportShareLinksRow{}
	for rows.Next() {
		var i ExportShareLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastAccessedAt,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportVersions = `-- name: ExportVersions :many
select v.id, v.user_id, v.part_id, v.text, v.origin, v.edited_at, v.recorded_at, v.applied, v.source_event_id, v.session_id from note_part_versions v join note_parts p on p.user_id = v.user_id and p.id = v.part_id
where v.user_id = $1 and p.note_id = any($2::uuid[]) order by v.part_id, v.edited_at, v.id
`

type ExportVersionsParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

func (q *Queries) ExportVersions(ctx context.Context, arg ExportVersionsParams) ([]NotePartVersion, error) {
	rows, err := q.db.Query(ctx, exportVersions, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotePartVersion{}
	for rows.Next() {
		var i NotePartVersion
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PartID,
			&i.Text,
			&i.Origin,
			&i.EditedAt,
			&i.RecordedAt,
			&i.Applied,
			&i.SourceEventID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
