// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	BlobID    uuid.UUID
	Filename  string
	MediaType string
	CreatedAt time.Time
}

type AuditLog struct {
	ID         int64
	At         time.Time
	ActorKind  string
	ActorID    uuid.NullUUID
	Action     string
	TargetKind *string
	TargetID   uuid.NullUUID
	Detail     []byte
}

type AuthThrottle struct {
	Key          string
	Failures     int32
	BlockedUntil *time.Time
	UpdatedAt    time.Time
}

type Blob struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Backend       string
	SizeBytes     int64
	ChunkSize     int32
	Sha256        []byte
	Complete      bool
	ReservedBytes int64
	CreatedAt     time.Time
	UploadID      uuid.NullUUID
}

type BlobChunk struct {
	UserID uuid.UUID
	BlobID uuid.UUID
	Idx    int32
	Data   []byte
}

type BotCredential struct {
	ID            uuid.UUID
	BotInstanceID uuid.UUID
	ClientID      string
	SecretHash    []byte
	Scopes        []string
	CreatedAt     time.Time
	DisabledAt    *time.Time
}

type BotInstance struct {
	ID             uuid.UUID
	Type           string
	Name           string
	IdentityDomain string
	Status         string
	LastSeenAt     *time.Time
	CreatedAt      time.Time
}

type BotOutbox struct {
	ID             uuid.UUID
	BotInstanceID  uuid.UUID
	Kind           string
	UserID         uuid.NullUUID
	ExternalUserID string
	ConversationID string
	Payload        []byte
	State          string
	Attempts       int32
	NextAttemptAt  time.Time
	LeaseExpiresAt *time.Time
	DueAt          *time.Time
	ReminderID     uuid.NullUUID
	CreatedAt      time.Time
	FinishedAt     *time.Time
	FailureReason  *string
}

type Category struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PageID    uuid.UUID
	Name      string
	Position  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

type Change struct {
	UserID     uuid.UUID
	Seq        int64
	EntityType string
	EntityID   uuid.UUID
	Op         string
	Version    *int32
	CreatedAt  time.Time
}

type ExternalIdentity struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	BotInstanceID  uuid.UUID
	BotType        string
	ExternalUserID string
	ConversationID *string
	ReminderTarget bool
	LinkedAt       time.Time
}

type IdempotencyKey struct {
	Scope       string
	Key         string
	RequestHash []byte
	Response    []byte
	CreatedAt   time.Time
}

type IngestEvent struct {
	BotInstanceID uuid.UUID
	EventID       string
	UserID        uuid.UUID
	ReceivedAt    time.Time
	Result        []byte
}

type Note struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CategoryID uuid.NullUUID
	Position   *string
	State      string
	DeletedAt  *time.Time
	CreatedAt  time.Time
	ReceivedAt time.Time
	UpdatedAt  time.Time
	Version    int32
}

type NotePart struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	NoteID               uuid.UUID
	Ordinal              int32
	Kind                 string
	Text                 *string
	AttachmentID         uuid.NullUUID
	FailedFilename       *string
	FailedSize           *int64
	FailedReason         *string
	AttachReason         string
	RelatedPartID        uuid.NullUUID
	CreatedAt            time.Time
	TextEditedAt         *time.Time
	SourceBotInstanceID  uuid.NullUUID
	SourceIdentityID     uuid.NullUUID
	SourceConversationID *string
	SourceMessageID      *string
	SourcePartIndex      pgtype.Int2
}

type NotePartVersion struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	PartID        uuid.UUID
	Text          string
	Origin        string
	EditedAt      time.Time
	RecordedAt    time.Time
	Applied       bool
	SourceEventID *string
	SessionID     uuid.NullUUID
}

type NoteSearch struct {
	NoteID uuid.UUID
	UserID uuid.UUID
	Body   string
	Doc    interface{}
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	Payload   []byte
	CreatedAt time.Time
	ReadAt    *time.Time
}

type OutboxMessage struct {
	BotInstanceID  uuid.UUID
	ConversationID string
	MessageID      string
	OutboxID       uuid.UUID
}

type Page struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Position   string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

type PairingCode struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	CodeHash      []byte
	BotInstanceID uuid.NullUUID
	BotType       string
	ExpiresAt     time.Time
	UsedAt        *time.Time
}

type Reminder struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	NoteID       uuid.UUID
	DueAt        time.Time
	Rrule        *string
	Tz           string
	State        string
	LastFiredAt  *time.Time
	ClaimedUntil *time.Time
	CreatedAt    time.Time
	Version      int32
}

type Session struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	ClientKind         string
	Label              string
	CreatedAt          time.Time
	LastRefreshedAt    time.Time
	ExpiresAt          time.Time
	AbsoluteExpiresAt  time.Time
	RefreshGeneration  int32
	PreviousValidUntil *time.Time
	RevokedAt          *time.Time
	RevokedReason      *string
}

type ShareLink struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	NoteID         uuid.UUID
	TokenHash      []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
	RevokedAt      *time.Time
	LastAccessedAt *time.Time
	ViewCount      int32
}

type UnlinkedSender struct {
	BotInstanceID  uuid.UUID
	ExternalUserID string
	LastNoticeAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	DisplayName  string
	Email        *string
	Status       string
	IsAdmin      bool
	PasswordHash *string
	Timezone     string
	Settings     []byte
	ChangeSeq    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Version      int32
}

type UserStorage struct {
	UserID        uuid.UUID
	UsedBytes     int64
	ReservedBytes int64
	QuotaBytes    *int64
}

type UserToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedBy uuid.NullUUID
}
