// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInbox = `-- name: CountInbox :one
select count(*) from notes where user_id = $1 and state = 'active' and category_id is null
`

func (q *Queries) CountInbox(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInbox, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getIngestEvent = `-- name: GetIngestEvent :one
select result from ingest_events where bot_instance_id = $1 and event_id = $2
`

type GetIngestEventParams struct {
	BotInstanceID uuid.UUID
	EventID       string
}

func (q *Queries) GetIngestEvent(ctx context.Context, arg GetIngestEventParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getIngestEvent, arg.BotInstanceID, arg.EventID)
	var result []byte
	err := row.Scan(&result)
	return result, err
}

const getNote = `-- name: GetNote :one
select id, user_id, category_id, position, state, deleted_at, created_at, received_at, updated_at, version from notes where id = $1 and user_id = $2
`

type GetNoteParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Position,
		&i.State,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.ReceivedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertIngestEvent = `-- name: InsertIngestEvent :execrows
insert into ingest_events (bot_instance_id, event_id, user_id, result) values ($1, $2, $3, $4)
on conflict do nothing
`

type InsertIngestEventParams struct {
	BotInstanceID uuid.UUID
	EventID       string
	UserID        uuid.UUID
	Result        []byte
}

func (q *Queries) InsertIngestEvent(ctx context.Context, arg InsertIngestEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIngestEvent,
		arg.BotInstanceID,
		arg.EventID,
		arg.UserID,
		arg.Result,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNote = `-- name: InsertNote :one
insert into notes (id, user_id, created_at, received_at) values ($1, $2, $3, $4) returning id, user_id, category_id, position, state, deleted_at, created_at, received_at, updated_at, version
`

type InsertNoteParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CreatedAt  time.Time
	ReceivedAt time.Time
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, insertNote,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ReceivedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Position,
		&i.State,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.ReceivedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertNotePart = `-- name: InsertNotePart :one
insert into note_parts (id, user_id, note_id, ordinal, kind, text, attachment_id, failed_filename, failed_size, failed_reason,
  attach_reason, related_part_id, created_at, source_bot_instance_id, source_identity_id, source_conversation_id,
  source_message_id, source_part_index)
values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) returning id, user_id, note_id, ordinal, kind, text, attachment_id, failed_filename, failed_size, failed_reason, attach_reason, related_part_id, created_at, text_edited_at, source_bot_instance_id, source_identity_id, source_conversation_id, source_message_id, source_part_index
`

type InsertNotePartParams struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	NoteID               uuid.UUID
	Ordinal              int32
	Kind                 string
	Text                 *string
	AttachmentID         uuid.NullUUID
	FailedFilename       *string
	FailedSize           *int64
	FailedReason         *string
	AttachReason         string
	RelatedPartID        uuid.NullUUID
	CreatedAt            time.Time
	SourceBotInstanceID  uuid.NullUUID
	SourceIdentityID     uuid.NullUUID
	SourceConversationID *string
	SourceMessageID      *string
	SourcePartIndex      pgtype.Int2
}

func (q *Queries) InsertNotePart(ctx context.Context, arg InsertNotePartParams) (NotePart, error) {
	row := q.db.QueryRow(ctx, insertNotePart,
		arg.ID,
		arg.UserID,
		arg.NoteID,
		arg.Ordinal,
		arg.Kind,
		arg.Text,
		arg.AttachmentID,
		arg.FailedFilename,
		arg.FailedSize,
		arg.FailedReason,
		arg.AttachReason,
		arg.RelatedPartID,
		arg.CreatedAt,
		arg.SourceBotInstanceID,
		arg.SourceIdentityID,
		arg.SourceConversationID,
		arg.SourceMessageID,
		arg.SourcePartIndex,
	)
	var i NotePart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.Ordinal,
		&i.Kind,
		&i.Text,
		&i.AttachmentID,
		&i.FailedFilename,
		&i.FailedSize,
		&i.FailedReason,
		&i.AttachReason,
		&i.RelatedPartID,
		&i.CreatedAt,
		&i.TextEditedAt,
		&i.SourceBotInstanceID,
		&i.SourceIdentityID,
		&i.SourceConversationID,
		&i.SourceMessageID,
		&i.SourcePartIndex,
	)
	return i, err
}

const listInbox = `-- name: ListInbox :many
select id, user_id, category_id, position, state, deleted_at, created_at, received_at, updated_at, version from notes
where user_id = $1 and state = 'active' and category_id is null
  and ($3::timestamptz is null or (created_at, id) < ($3::timestamptz, $4::uuid))
order by created_at desc, id desc
limit $2
`

type ListInboxParams struct {
	UserID       uuid.UUID
	Limit        int32
	AfterCreated *time.Time
	AfterID      uuid.NullUUID
}

func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listInbox,
		arg.UserID,
		arg.Limit,
		arg.AfterCreated,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Position,
			&i.State,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.ReceivedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteParts = `-- name: ListNoteParts :many
select id, user_id, note_id, ordinal, kind, text, attachment_id, failed_filename, failed_size, failed_reason, attach_reason, related_part_id, created_at, text_edited_at, source_bot_instance_id, source_identity_id, source_conversation_id, source_message_id, source_part_index from note_parts where note_id = any($1::uuid[]) order by note_id, ordinal
`

func (q *Queries) ListNoteParts(ctx context.Context, dollar_1 []uuid.UUID) ([]NotePart, error) {
	rows, err := q.db.Query(ctx, listNoteParts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotePart{}
	for rows.Next() {
		var i NotePart
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteID,
			&i.Ordinal,
			&i.Kind,
			&i.Text,
			&i.AttachmentID,
			&i.FailedFilename,
			&i.FailedSize,
			&i.FailedReason,
			&i.AttachReason,
			&i.RelatedPartID,
			&i.CreatedAt,
			&i.TextEditedAt,
			&i.SourceBotInstanceID,
			&i.SourceIdentityID,
			&i.SourceConversationID,
			&i.SourceMessageID,
			&i.SourcePartIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngestResult = `-- name: UpdateIngestResult :exec
update ingest_events set result = $3 where bot_instance_id = $1 and event_id = $2
`

type UpdateIngestResultParams struct {
	BotInstanceID uuid.UUID
	EventID       string
	Result        []byte
}

func (q *Queries) UpdateIngestResult(ctx context.Context, arg UpdateIngestResultParams) error {
	_, err := q.db.Exec(ctx, updateIngestResult, arg.BotInstanceID, arg.EventID, arg.Result)
	return err
}
