// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimOutbox = `-- name: ClaimOutbox :many
update bot_outbox set state = 'claimed', lease_expires_at = $1::timestamptz
where id in (
  select o.id from bot_outbox o
  left join users u on u.id = o.user_id
  where o.bot_instance_id = $2
    and ((o.state = 'queued' and o.next_attempt_at <= $3::timestamptz)
         or (o.state = 'claimed' and o.lease_expires_at < $3::timestamptz))
    and (o.user_id is null or u.status = 'active')
  order by o.created_at
  limit $4
  for update of o skip locked)
returning id, bot_instance_id, kind, user_id, external_user_id, conversation_id, payload, state, attempts, next_attempt_at, lease_expires_at, due_at, reminder_id, created_at, finished_at, failure_reason
`

type ClaimOutboxParams struct {
	Lease    time.Time
	Instance uuid.UUID
	Now      time.Time
	MaxItems int32
}

func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]BotOutbox, error) {
	rows, err := q.db.Query(ctx, claimOutbox,
		arg.Lease,
		arg.Instance,
		arg.Now,
		arg.MaxItems,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotOutbox{}
	for rows.Next() {
		var i BotOutbox
		if err := rows.Scan(
			&i.ID,
			&i.BotInstanceID,
			&i.Kind,
			&i.UserID,
			&i.ExternalUserID,
			&i.ConversationID,
			&i.Payload,
			&i.State,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LeaseExpiresAt,
			&i.DueAt,
			&i.ReminderID,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireOutboxItem = `-- name: ExpireOutboxItem :execrows
update bot_outbox set state = 'expired', finished_at = $2, lease_expires_at = null, failure_reason = 'expired'
where id = $1 and state in ('queued', 'claimed')
`

type ExpireOutboxItemParams struct {
	ID         uuid.UUID
	FinishedAt *time.Time
}

func (q *Queries) ExpireOutboxItem(ctx context.Context, arg ExpireOutboxItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireOutboxItem, arg.ID, arg.FinishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failOutbox = `-- name: FailOutbox :execrows
update bot_outbox set state = 'failed', finished_at = $3, lease_expires_at = null, failure_reason = $4
where id = $1 and bot_instance_id = $2 and state = 'claimed'
`

type FailOutboxParams struct {
	ID            uuid.UUID
	BotInstanceID uuid.UUID
	FinishedAt    *time.Time
	FailureReason *string
}

func (q *Queries) FailOutbox(ctx context.Context, arg FailOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, failOutbox,
		arg.ID,
		arg.BotInstanceID,
		arg.FinishedAt,
		arg.FailureReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClaimedOutbox = `-- name: GetClaimedOutbox :one
select id, bot_instance_id, kind, user_id, external_user_id, conversation_id, payload, state, attempts, next_attempt_at, lease_expires_at, due_at, reminder_id, created_at, finished_at, failure_reason from bot_outbox where id = $1 and bot_instance_id = $2 and state = 'claimed'
`

type GetClaimedOutboxParams struct {
	ID            uuid.UUID
	BotInstanceID uuid.UUID
}

func (q *Queries) GetClaimedOutbox(ctx context.Context, arg GetClaimedOutboxParams) (BotOutbox, error) {
	row := q.db.QueryRow(ctx, getClaimedOutbox, arg.ID, arg.BotInstanceID)
	var i BotOutbox
	err := row.Scan(
		&i.ID,
		&i.BotInstanceID,
		&i.Kind,
		&i.UserID,
		&i.ExternalUserID,
		&i.ConversationID,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseExpiresAt,
		&i.DueAt,
		&i.ReminderID,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.FailureReason,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :exec
insert into notifications (id, user_id, kind, payload) values ($1, $2, $3, $4)
`

type InsertNotificationParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Kind    string
	Payload []byte
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Payload,
	)
	return err
}

const insertOutboxMessage = `-- name: InsertOutboxMessage :exec
insert into outbox_messages (bot_instance_id, conversation_id, message_id, outbox_id) values ($1, $2, $3, $4)
on conflict do nothing
`

type InsertOutboxMessageParams struct {
	BotInstanceID  uuid.UUID
	ConversationID string
	MessageID      string
	OutboxID       uuid.UUID
}

func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.Exec(ctx, insertOutboxMessage,
		arg.BotInstanceID,
		arg.ConversationID,
		arg.MessageID,
		arg.OutboxID,
	)
	return err
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :execrows
update bot_outbox set state = 'delivered', finished_at = $3, lease_expires_at = null
where id = $1 and bot_instance_id = $2 and state = 'claimed'
`

type MarkOutboxDeliveredParams struct {
	ID            uuid.UUID
	BotInstanceID uuid.UUID
	FinishedAt    *time.Time
}

func (q *Queries) MarkOutboxDelivered(ctx context.Context, arg MarkOutboxDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxDelivered, arg.ID, arg.BotInstanceID, arg.FinishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const outboxDepth = `-- name: OutboxDepth :many
select bot_instance_id, state, count(*)::bigint as n from bot_outbox group by bot_instance_id, state
`

type OutboxDepthRow struct {
	BotInstanceID uuid.UUID
	State         string
	N             int64
}

func (q *Queries) OutboxDepth(ctx context.Context) ([]OutboxDepthRow, error) {
	rows, err := q.db.Query(ctx, outboxDepth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxDepthRow{}
	for rows.Next() {
		var i OutboxDepthRow
		if err := rows.Scan(&i.BotInstanceID, &i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueOutbox = `-- name: RequeueOutbox :execrows
update bot_outbox set state = 'queued', attempts = attempts + 1, next_attempt_at = $3, lease_expires_at = null, failure_reason = $4
where id = $1 and bot_instance_id = $2 and state = 'claimed'
`

type RequeueOutboxParams struct {
	ID            uuid.UUID
	BotInstanceID uuid.UUID
	NextAttemptAt time.Time
	FailureReason *string
}

func (q *Queries) RequeueOutbox(ctx context.Context, arg RequeueOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueOutbox,
		arg.ID,
		arg.BotInstanceID,
		arg.NextAttemptAt,
		arg.FailureReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const staleOutbox = `-- name: StaleOutbox :many
select id, user_id, kind from bot_outbox
where state in ('queued', 'claimed') and created_at < $1
order by created_at limit 200
`

type StaleOutboxRow struct {
	ID     uuid.UUID
	UserID uuid.NullUUID
	Kind   string
}

func (q *Queries) StaleOutbox(ctx context.Context, createdAt time.Time) ([]StaleOutboxRow, error) {
	rows, err := q.db.Query(ctx, staleOutbox, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaleOutboxRow{}
	for rows.Next() {
		var i StaleOutboxRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
