// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probe.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const probeUser = `-- name: ProbeUser :one
select id, username, display_name, email, status, is_admin, password_hash, timezone, settings, change_seq, created_at, updated_at, version from users where id = $1
`

func (q *Queries) ProbeUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, probeUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Timezone,
		&i.Settings,
		&i.ChangeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
