// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceReminder = `-- name: AdvanceReminder :exec
update reminders set due_at = $2, last_fired_at = $3, claimed_until = null, version = version + 1 where id = $1
`

type AdvanceReminderParams struct {
	ID          uuid.UUID
	DueAt       time.Time
	LastFiredAt *time.Time
}

func (q *Queries) AdvanceReminder(ctx context.Context, arg AdvanceReminderParams) error {
	_, err := q.db.Exec(ctx, advanceReminder, arg.ID, arg.DueAt, arg.LastFiredAt)
	return err
}

const claimDueReminders = `-- name: ClaimDueReminders :many
update reminders set claimed_until = $1::timestamptz
where id in (
  select r.id from reminders r
  where r.state = 'pending' and r.due_at <= $2::timestamptz
    and (r.claimed_until is null or r.claimed_until < $2::timestamptz)
    and exists (select 1 from users u where u.id = r.user_id and u.status = 'active')
  order by r.due_at limit 100
  for update skip locked)
returning id, user_id
`

type ClaimDueRemindersParams struct {
	Lease time.Time
	Now   time.Time
}

type ClaimDueRemindersRow struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ClaimDueReminders(ctx context.Context, arg ClaimDueRemindersParams) ([]ClaimDueRemindersRow, error) {
	rows, err := q.db.Query(ctx, claimDueReminders, arg.Lease, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueRemindersRow{}
	for rows.Next() {
		var i ClaimDueRemindersRow
		if err := rows.Scan(&i.ID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNoteReminders = `-- name: CountNoteReminders :one
select count(*) from reminders where user_id = $1 and note_id = $2
`

type CountNoteRemindersParams struct {
	UserID uuid.UUID
	NoteID uuid.UUID
}

func (q *Queries) CountNoteReminders(ctx context.Context, arg CountNoteRemindersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteReminders, arg.UserID, arg.NoteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
select count(*) from notifications where user_id = $1 and read_at is null
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserReminders = `-- name: CountUserReminders :one
select count(*) from reminders where user_id = $1 and state in ('pending', 'suspended')
`

func (q *Queries) CountUserReminders(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserReminders, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :execrows
delete from notifications where created_at < $1 and read_at is not null
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldNotifications, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReminder = `-- name: DeleteReminder :one
delete from reminders where id = $1 and user_id = $2 returning note_id
`

type DeleteReminderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteReminder(ctx context.Context, arg DeleteReminderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteReminder, arg.ID, arg.UserID)
	var note_id uuid.UUID
	err := row.Scan(&note_id)
	return note_id, err
}

const finishReminder = `-- name: FinishReminder :one
update reminders set state = 'done', claimed_until = null, version = version + 1
where id = $1 and user_id = $2 and state in ('pending', 'fired') returning id, user_id, note_id, due_at, rrule, tz, state, last_fired_at, claimed_until, created_at, version
`

type FinishReminderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) FinishReminder(ctx context.Context, arg FinishReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, finishReminder, arg.ID, arg.UserID)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.DueAt,
		&i.Rrule,
		&i.Tz,
		&i.State,
		&i.LastFiredAt,
		&i.ClaimedUntil,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getDueReminder = `-- name: GetDueReminder :one
select id, user_id, note_id, due_at, rrule, tz, state, last_fired_at, claimed_until, created_at, version from reminders where id = $1 and user_id = $2 and state = 'pending' and due_at <= $3
`

type GetDueReminderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	DueAt  time.Time
}

func (q *Queries) GetDueReminder(ctx context.Context, arg GetDueReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, getDueReminder, arg.ID, arg.UserID, arg.DueAt)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.DueAt,
		&i.Rrule,
		&i.Tz,
		&i.State,
		&i.LastFiredAt,
		&i.ClaimedUntil,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getReminder = `-- name: GetReminder :one
select id, user_id, note_id, due_at, rrule, tz, state, last_fired_at, claimed_until, created_at, version from reminders where id = $1 and user_id = $2
`

type GetReminderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetReminder(ctx context.Context, arg GetReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, getReminder, arg.ID, arg.UserID)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.DueAt,
		&i.Rrule,
		&i.Tz,
		&i.State,
		&i.LastFiredAt,
		&i.ClaimedUntil,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const insertReminder = `-- name: InsertReminder :one
insert into reminders (id, user_id, note_id, due_at, rrule, tz, created_at) values ($1, $2, $3, $4, $5, $6, $7) returning id, user_id, note_id, due_at, rrule, tz, state, last_fired_at, claimed_until, created_at, version
`

type InsertReminderParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	NoteID    uuid.UUID
	DueAt     time.Time
	Rrule     *string
	Tz        string
	CreatedAt time.Time
}

func (q *Queries) InsertReminder(ctx context.Context, arg InsertReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, insertReminder,
		arg.ID,
		arg.UserID,
		arg.NoteID,
		arg.DueAt,
		arg.Rrule,
		arg.Tz,
		arg.CreatedAt,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.DueAt,
		&i.Rrule,
		&i.Tz,
		&i.State,
		&i.LastFiredAt,
		&i.ClaimedUntil,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const insertReminderOutbox = `-- name: InsertReminderOutbox :exec
insert into bot_outbox (id, bot_instance_id, kind, user_id, external_user_id, conversation_id, payload, next_attempt_at, due_at, reminder_id)
values ($1, $2, 'reminder', $3, $4, $5, $6, $7, $8, $9)
`

type InsertReminderOutboxParams struct {
	ID             uuid.UUID
	BotInstanceID  uuid.UUID
	UserID         uuid.NullUUID
	ExternalUserID string
	ConversationID string
	Payload        []byte
	NextAttemptAt  time.Time
	DueAt          *time.Time
	ReminderID     uuid.NullUUID
}

func (q *Queries) InsertReminderOutbox(ctx context.Context, arg InsertReminderOutboxParams) error {
	_, err := q.db.Exec(ctx, insertReminderOutbox,
		arg.ID,
		arg.BotInstanceID,
		arg.UserID,
		arg.ExternalUserID,
		arg.ConversationID,
		arg.Payload,
		arg.NextAttemptAt,
		arg.DueAt,
		arg.ReminderID,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
select id, user_id, kind, payload, created_at, read_at from notifications where user_id = $1 and (not $2::boolean or read_at is null) order by created_at desc, id limit 100
`

type ListNotificationsParams struct {
	UserID     uuid.UUID
	UnreadOnly bool
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.UnreadOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersForNotes = `-- name: ListRemindersForNotes :many
select id, user_id, note_id, due_at, rrule, tz, state, last_fired_at, claimed_until, created_at, version from reminders where note_id = any($1::uuid[]) order by due_at, id
`

func (q *Queries) ListRemindersForNotes(ctx context.Context, ids []uuid.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listRemindersForNotes, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteID,
			&i.DueAt,
			&i.Rrule,
			&i.Tz,
			&i.State,
			&i.LastFiredAt,
			&i.ClaimedUntil,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingReminders = `-- name: ListUpcomingReminders :many
select r.id, r.user_id, r.note_id, r.due_at, r.rrule, r.tz, r.state, r.last_fired_at, r.claimed_until, r.created_at, r.version, coalesce((select left(p.text, 140) from note_parts p where p.user_id = r.user_id and p.note_id = r.note_id and p.kind = 'text'
                      order by p.ordinal limit 1), '')::text as excerpt
from reminders r join notes n on n.user_id = r.user_id and n.id = r.note_id
where r.user_id = $1 and r.state = 'pending' and n.state = 'active'
order by r.due_at, r.id limit 200
`

type ListUpcomingRemindersRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	NoteID       uuid.UUID
	DueAt        time.Time
	Rrule        *string
	Tz           string
	State        string
	LastFiredAt  *time.Time
	ClaimedUntil *time.Time
	CreatedAt    time.Time
	Version      int32
	Excerpt      string
}

func (q *Queries) ListUpcomingReminders(ctx context.Context, userID uuid.UUID) ([]ListUpcomingRemindersRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingReminders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingRemindersRow{}
	for rows.Next() {
		var i ListUpcomingRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteID,
			&i.DueAt,
			&i.Rrule,
			&i.Tz,
			&i.State,
			&i.LastFiredAt,
			&i.ClaimedUntil,
			&i.CreatedAt,
			&i.Version,
			&i.Excerpt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :many
update notifications set read_at = $2 where user_id = $1 and read_at is null and ($3::uuid[] is null or id = any($3::uuid[])) returning id
`

type MarkNotificationsReadParams struct {
	UserID uuid.UUID
	ReadAt *time.Time
	Ids    []uuid.UUID
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, markNotificationsRead, arg.UserID, arg.ReadAt, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderFired = `-- name: MarkReminderFired :exec
update reminders set state = 'fired', last_fired_at = $2, claimed_until = null, version = version + 1 where id = $1
`

type MarkReminderFiredParams struct {
	ID          uuid.UUID
	LastFiredAt *time.Time
}

func (q *Queries) MarkReminderFired(ctx context.Context, arg MarkReminderFiredParams) error {
	_, err := q.db.Exec(ctx, markReminderFired, arg.ID, arg.LastFiredAt)
	return err
}

const noteAttachmentInfo = `-- name: NoteAttachmentInfo :many
select a.id, a.filename, a.media_type, b.size_bytes from note_parts p
join attachments a on a.user_id = p.user_id and a.id = p.attachment_id
join blobs b on b.user_id = a.user_id and b.id = a.blob_id
where p.user_id = $1 and p.note_id = $2 and p.kind = 'attachment' order by p.ordinal
`

type NoteAttachmentInfoParams struct {
	UserID uuid.UUID
	NoteID uuid.UUID
}

type NoteAttachmentInfoRow struct {
	ID        uuid.UUID
	Filename  string
	MediaType string
	SizeBytes int64
}

func (q *Queries) NoteAttachmentInfo(ctx context.Context, arg NoteAttachmentInfoParams) ([]NoteAttachmentInfoRow, error) {
	rows, err := q.db.Query(ctx, noteAttachmentInfo, arg.UserID, arg.NoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NoteAttachmentInfoRow{}
	for rows.Next() {
		var i NoteAttachmentInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.MediaType,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noteExcerpt = `-- name: NoteExcerpt :one
select coalesce((select left(p.text, 300) from note_parts p where p.user_id = $1 and p.note_id = $2 and p.kind = 'text' order by p.ordinal limit 1), '')::text
`

type NoteExcerptParams struct {
	UserID uuid.UUID
	NoteID uuid.UUID
}

func (q *Queries) NoteExcerpt(ctx context.Context, arg NoteExcerptParams) (string, error) {
	row := q.db.QueryRow(ctx, noteExcerpt, arg.UserID, arg.NoteID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const noticeTargets = `-- name: NoticeTargets :many
select id, bot_instance_id, external_user_id, conversation_id from external_identities
where user_id = $1 and conversation_id is not null order by linked_at
`

type NoticeTargetsRow struct {
	ID             uuid.UUID
	BotInstanceID  uuid.UUID
	ExternalUserID string
	ConversationID *string
}

func (q *Queries) NoticeTargets(ctx context.Context, userID uuid.UUID) ([]NoticeTargetsRow, error) {
	rows, err := q.db.Query(ctx, noticeTargets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NoticeTargetsRow{}
	for rows.Next() {
		var i NoticeTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.BotInstanceID,
			&i.ExternalUserID,
			&i.ConversationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reminderByChatMessage = `-- name: ReminderByChatMessage :one
select o.reminder_id from outbox_messages m join bot_outbox o on o.id = m.outbox_id
where m.bot_instance_id = $1 and m.conversation_id = $2 and m.message_id = $3 and o.user_id = $4 and o.reminder_id is not null
`

type ReminderByChatMessageParams struct {
	BotInstanceID  uuid.UUID
	ConversationID string
	MessageID      string
	UserID         uuid.NullUUID
}

func (q *Queries) ReminderByChatMessage(ctx context.Context, arg ReminderByChatMessageParams) (uuid.NullUUID, error) {
	row := q.db.QueryRow(ctx, reminderByChatMessage,
		arg.BotInstanceID,
		arg.ConversationID,
		arg.MessageID,
		arg.UserID,
	)
	var reminder_id uuid.NullUUID
	err := row.Scan(&reminder_id)
	return reminder_id, err
}

const reminderTargets = `-- name: ReminderTargets :many
select id, bot_instance_id, external_user_id, conversation_id from external_identities
where user_id = $1 and reminder_target and conversation_id is not null order by linked_at
`

type ReminderTargetsRow struct {
	ID             uuid.UUID
	BotInstanceID  uuid.UUID
	ExternalUserID string
	ConversationID *string
}

func (q *Queries) ReminderTargets(ctx context.Context, userID uuid.UUID) ([]ReminderTargetsRow, error) {
	rows, err := q.db.Query(ctx, reminderTargets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReminderTargetsRow{}
	for rows.Next() {
		var i ReminderTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.BotInstanceID,
			&i.ExternalUserID,
			&i.ConversationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreReminder = `-- name: RestoreReminder :exec
update reminders set state = $2, due_at = $3, version = version + 1 where id = $1
`

type RestoreReminderParams struct {
	ID    uuid.UUID
	State string
	DueAt time.Time
}

func (q *Queries) RestoreReminder(ctx context.Context, arg RestoreReminderParams) error {
	_, err := q.db.Exec(ctx, restoreReminder, arg.ID, arg.State, arg.DueAt)
	return err
}

const setReminder = `-- name: SetReminder :one
update reminders set due_at = $3, rrule = $4, tz = $5, state = 'pending', claimed_until = null, version = version + 1
where id = $1 and user_id = $2 returning id, user_id, note_id, due_at, rrule, tz, state, last_fired_at, claimed_until, created_at, version
`

type SetReminderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	DueAt  time.Time
	Rrule  *string
	Tz     string
}

func (q *Queries) SetReminder(ctx context.Context, arg SetReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, setReminder,
		arg.ID,
		arg.UserID,
		arg.DueAt,
		arg.Rrule,
		arg.Tz,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.DueAt,
		&i.Rrule,
		&i.Tz,
		&i.State,
		&i.LastFiredAt,
		&i.ClaimedUntil,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const snoozeReminder = `-- name: SnoozeReminder :one
update reminders set due_at = $3, state = 'pending', claimed_until = null, version = version + 1
where id = $1 and user_id = $2 and state in ('pending', 'fired', 'done') returning id, user_id, note_id, due_at, rrule, tz, state, last_fired_at, claimed_until, created_at, version
`

type SnoozeReminderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	DueAt  time.Time
}

func (q *Queries) SnoozeReminder(ctx context.Context, arg SnoozeReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, snoozeReminder, arg.ID, arg.UserID, arg.DueAt)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.DueAt,
		&i.Rrule,
		&i.Tz,
		&i.State,
		&i.LastFiredAt,
		&i.ClaimedUntil,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const suspendNoteReminders = `-- name: SuspendNoteReminders :many
update reminders set state = 'suspended', claimed_until = null, version = version + 1
where user_id = $1 and note_id = $2 and state = 'pending' returning id
`

type SuspendNoteRemindersParams struct {
	UserID uuid.UUID
	NoteID uuid.UUID
}

func (q *Queries) SuspendNoteReminders(ctx context.Context, arg SuspendNoteRemindersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, suspendNoteReminders, arg.UserID, arg.NoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suspendedNoteReminders = `-- name: SuspendedNoteReminders :many
select id, user_id, note_id, due_at, rrule, tz, state, last_fired_at, claimed_until, created_at, version from reminders where user_id = $1 and note_id = $2 and state = 'suspended'
`

type SuspendedNoteRemindersParams struct {
	UserID uuid.UUID
	NoteID uuid.UUID
}

func (q *Queries) SuspendedNoteReminders(ctx context.Context, arg SuspendedNoteRemindersParams) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, suspendedNoteReminders, arg.UserID, arg.NoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteID,
			&i.DueAt,
			&i.Rrule,
			&i.Tz,
			&i.State,
			&i.LastFiredAt,
			&i.ClaimedUntil,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
