// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteOldSessions = `-- name: DeleteOldSessions :execrows
delete from sessions where coalesce(revoked_at, expires_at) < $1
`

func (q *Queries) DeleteOldSessions(ctx context.Context, revokedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldSessions, revokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
select id, user_id, client_kind, label, created_at, last_refreshed_at, expires_at, absolute_expires_at, refresh_generation, previous_valid_until, revoked_at, revoked_reason from sessions where id = $1 for update
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientKind,
		&i.Label,
		&i.CreatedAt,
		&i.LastRefreshedAt,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RefreshGeneration,
		&i.PreviousValidUntil,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getSessionPrincipal = `-- name: GetSessionPrincipal :one
select s.id, s.user_id, s.client_kind, s.expires_at, s.absolute_expires_at, s.revoked_at,
       u.status, u.is_admin, u.username, u.display_name, u.timezone
from sessions s join users u on u.id = s.user_id
where s.id = $1
`

type GetSessionPrincipalRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	ClientKind        string
	ExpiresAt         time.Time
	AbsoluteExpiresAt time.Time
	RevokedAt         *time.Time
	Status            string
	IsAdmin           bool
	Username          string
	DisplayName       string
	Timezone          string
}

func (q *Queries) GetSessionPrincipal(ctx context.Context, id uuid.UUID) (GetSessionPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getSessionPrincipal, id)
	var i GetSessionPrincipalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientKind,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.Status,
		&i.IsAdmin,
		&i.Username,
		&i.DisplayName,
		&i.Timezone,
	)
	return i, err
}

const getUserSession = `-- name: GetUserSession :one
select id, user_id from sessions where id = $1 and user_id = $2
`

type GetUserSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetUserSessionRow struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetUserSession(ctx context.Context, arg GetUserSessionParams) (GetUserSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserSession, arg.ID, arg.UserID)
	var i GetUserSessionRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
insert into sessions (id, user_id, client_kind, label, created_at, last_refreshed_at, expires_at, absolute_expires_at)
values ($1, $2, $3, $4, $5, $5, $6, $7)
`

type InsertSessionParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	ClientKind        string
	Label             string
	CreatedAt         time.Time
	ExpiresAt         time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.ClientKind,
		arg.Label,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const listUserSessions = `-- name: ListUserSessions :many
select id, client_kind, label, created_at, last_refreshed_at, expires_at
from sessions where user_id = $1 and revoked_at is null and expires_at > $2
order by last_refreshed_at desc
`

type ListUserSessionsParams struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type ListUserSessionsRow struct {
	ID              uuid.UUID
	ClientKind      string
	Label           string
	CreatedAt       time.Time
	LastRefreshedAt time.Time
	ExpiresAt       time.Time
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientKind,
			&i.Label,
			&i.CreatedAt,
			&i.LastRefreshedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifySessions = `-- name: NotifySessions :exec
select pg_notify('nk_sessions', $1::text)
`

func (q *Queries) NotifySessions(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, notifySessions, dollar_1)
	return err
}

const revokeSession = `-- name: RevokeSession :execrows
update sessions set revoked_at = $2, revoked_reason = $3 where id = $1 and revoked_at is null
`

type RevokeSessionParams struct {
	ID            uuid.UUID
	RevokedAt     *time.Time
	RevokedReason *string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt, arg.RevokedReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :many
update sessions set revoked_at = $2, revoked_reason = $3
where user_id = $1 and revoked_at is null and ($4::uuid is null or id <> $4::uuid)
returning id
`

type RevokeUserSessionsParams struct {
	UserID        uuid.UUID
	RevokedAt     *time.Time
	RevokedReason *string
	Except        uuid.NullUUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeUserSessions,
		arg.UserID,
		arg.RevokedAt,
		arg.RevokedReason,
		arg.Except,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateSession = `-- name: RotateSession :execrows
update sessions set refresh_generation = refresh_generation + 1, previous_valid_until = $3,
  last_refreshed_at = $4, expires_at = $5
where id = $1 and refresh_generation = $2 and revoked_at is null
`

type RotateSessionParams struct {
	ID                 uuid.UUID
	RefreshGeneration  int32
	PreviousValidUntil *time.Time
	LastRefreshedAt    time.Time
	ExpiresAt          time.Time
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSession,
		arg.ID,
		arg.RefreshGeneration,
		arg.PreviousValidUntil,
		arg.LastRefreshedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
