// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveShareLinks = `-- name: CountActiveShareLinks :one
select count(*) from share_links where user_id = $1 and revoked_at is null and expires_at > $2
`

type CountActiveShareLinksParams struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CountActiveShareLinks(ctx context.Context, arg CountActiveShareLinksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveShareLinks, arg.UserID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShareLinksCreatedSince = `-- name: CountShareLinksCreatedSince :one
select count(*) from share_links where user_id = $1 and created_at > $2
`

type CountShareLinksCreatedSinceParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CountShareLinksCreatedSince(ctx context.Context, arg CountShareLinksCreatedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShareLinksCreatedSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertShareLink = `-- name: InsertShareLink :one
insert into share_links (id, user_id, note_id, token_hash, created_at, expires_at)
values ($1, $2, $3, $4, $5, $6) returning id, user_id, note_id, token_hash, created_at, expires_at, revoked_at, last_accessed_at, view_count
`

type InsertShareLinkParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	NoteID    uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertShareLink(ctx context.Context, arg InsertShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, insertShareLink,
		arg.ID,
		arg.UserID,
		arg.NoteID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastAccessedAt,
		&i.ViewCount,
	)
	return i, err
}

const listShareLinks = `-- name: ListShareLinks :many
select l.id, l.note_id, l.created_at, l.expires_at, l.last_accessed_at, l.view_count,
       n.state as note_state,
       coalesce((select left(p.text, 140) from note_parts p where p.user_id = l.user_id and p.note_id = l.note_id and p.kind = 'text'
                 order by p.ordinal limit 1), '')::text as excerpt
from share_links l
join notes n on n.user_id = l.user_id and n.id = l.note_id
where l.user_id = $1 and l.revoked_at is null and l.expires_at > $2::timestamptz
  and ($3::uuid is null or l.note_id = $3::uuid)
order by l.created_at desc, l.id
`

type ListShareLinksParams struct {
	UserID uuid.UUID
	Now    time.Time
	NoteID uuid.NullUUID
}

type ListShareLinksRow struct {
	ID             uuid.UUID
	NoteID         uuid.UUID
	CreatedAt      time.Time
	ExpiresAt      time.Time
	LastAccessedAt *time.Time
	ViewCount      int32
	NoteState      string
	Excerpt        string
}

func (q *Queries) ListShareLinks(ctx context.Context, arg ListShareLinksParams) ([]ListShareLinksRow, error) {
	rows, err := q.db.Query(ctx, listShareLinks, arg.UserID, arg.Now, arg.NoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShareLinksRow{}
	for rows.Next() {
		var i ListShareLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastAccessedAt,
			&i.ViewCount,
			&i.NoteState,
			&i.Excerpt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupShare = `-- name: LookupShare :one
select l.id, l.user_id, l.note_id, l.expires_at
from share_links l join users u on u.id = l.user_id
where l.token_hash = $1 and l.revoked_at is null and l.expires_at > $2 and u.status = 'active'
`

type LookupShareParams struct {
	TokenHash []byte
	ExpiresAt time.Time
}

type LookupShareRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	NoteID    uuid.UUID
	ExpiresAt time.Time
}

// A link is valid only as a live condition: not revoked, not expired, and the owner active. The
// note's own state is checked afterwards, under the owner's row-level security (CORE-SH5).
func (q *Queries) LookupShare(ctx context.Context, arg LookupShareParams) (LookupShareRow, error) {
	row := q.db.QueryRow(ctx, lookupShare, arg.TokenHash, arg.ExpiresAt)
	var i LookupShareRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.ExpiresAt,
	)
	return i, err
}

const noteHasAttachment = `-- name: NoteHasAttachment :one
select exists(select 1 from note_parts where user_id = $1 and note_id = $2 and attachment_id = $3)
`

type NoteHasAttachmentParams struct {
	UserID       uuid.UUID
	NoteID       uuid.UUID
	AttachmentID uuid.NullUUID
}

func (q *Queries) NoteHasAttachment(ctx context.Context, arg NoteHasAttachmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, noteHasAttachment, arg.UserID, arg.NoteID, arg.AttachmentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const purgeShareLinks = `-- name: PurgeShareLinks :execrows
delete from share_links where expires_at < $1 or revoked_at < $1
`

func (q *Queries) PurgeShareLinks(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeShareLinks, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllShareLinks = `-- name: RevokeAllShareLinks :many
update share_links set revoked_at = $2 where user_id = $1 and revoked_at is null and expires_at > $2 returning id
`

type RevokeAllShareLinksParams struct {
	UserID    uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeAllShareLinks(ctx context.Context, arg RevokeAllShareLinksParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeAllShareLinks, arg.UserID, arg.RevokedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShareLink = `-- name: RevokeShareLink :one
update share_links set revoked_at = $3 where id = $1 and user_id = $2 and revoked_at is null and expires_at > $3 returning id, note_id
`

type RevokeShareLinkParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	RevokedAt *time.Time
}

type RevokeShareLinkRow struct {
	ID     uuid.UUID
	NoteID uuid.UUID
}

func (q *Queries) RevokeShareLink(ctx context.Context, arg RevokeShareLinkParams) (RevokeShareLinkRow, error) {
	row := q.db.QueryRow(ctx, revokeShareLink, arg.ID, arg.UserID, arg.RevokedAt)
	var i RevokeShareLinkRow
	err := row.Scan(&i.ID, &i.NoteID)
	return i, err
}

const shareLinkIDsOfNote = `-- name: ShareLinkIDsOfNote :many
select id from share_links where user_id = $1 and note_id = $2
`

type ShareLinkIDsOfNoteParams struct {
	UserID uuid.UUID
	NoteID uuid.UUID
}

func (q *Queries) ShareLinkIDsOfNote(ctx context.Context, arg ShareLinkIDsOfNoteParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, shareLinkIDsOfNote, arg.UserID, arg.NoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchShareLink = `-- name: TouchShareLink :exec
update share_links set view_count = view_count + 1, last_accessed_at = $2 where id = $1
`

type TouchShareLinkParams struct {
	ID             uuid.UUID
	LastAccessedAt *time.Time
}

func (q *Queries) TouchShareLink(ctx context.Context, arg TouchShareLinkParams) error {
	_, err := q.db.Exec(ctx, touchShareLink, arg.ID, arg.LastAccessedAt)
	return err
}
