// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeUserToken = `-- name: ConsumeUserToken :one
update user_tokens set used_at = $3
where token_hash = $1 and kind = $2 and used_at is null and expires_at > $3
returning user_id
`

type ConsumeUserTokenParams struct {
	TokenHash []byte
	Kind      string
	UsedAt    *time.Time
}

func (q *Queries) ConsumeUserToken(ctx context.Context, arg ConsumeUserTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeUserToken, arg.TokenHash, arg.Kind, arg.UsedAt)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteUserTokens = `-- name: DeleteUserTokens :exec
delete from user_tokens where user_id = $1 and kind = $2
`

type DeleteUserTokensParams struct {
	UserID uuid.UUID
	Kind   string
}

func (q *Queries) DeleteUserTokens(ctx context.Context, arg DeleteUserTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUserTokens, arg.UserID, arg.Kind)
	return err
}

const ensureThrottle = `-- name: EnsureThrottle :exec
insert into auth_throttle (key, failures, blocked_until, updated_at) values ($1, 0, null, $2) on conflict (key) do nothing
`

type EnsureThrottleParams struct {
	Key       string
	UpdatedAt time.Time
}

// The three statements below are used together in one transaction, so that counting an attempt is
// serialised per key by the row lock (SR-001).
func (q *Queries) EnsureThrottle(ctx context.Context, arg EnsureThrottleParams) error {
	_, err := q.db.Exec(ctx, ensureThrottle, arg.Key, arg.UpdatedAt)
	return err
}

const getThrottle = `-- name: GetThrottle :one
select failures, blocked_until, updated_at from auth_throttle where key = $1
`

type GetThrottleRow struct {
	Failures     int32
	BlockedUntil *time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetThrottle(ctx context.Context, key string) (GetThrottleRow, error) {
	row := q.db.QueryRow(ctx, getThrottle, key)
	var i GetThrottleRow
	err := row.Scan(&i.Failures, &i.BlockedUntil, &i.UpdatedAt)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
insert into audit_log (actor_kind, actor_id, action, target_kind, target_id, detail)
values ($1, $2, $3, $4, $5, $6)
`

type InsertAuditParams struct {
	ActorKind  string
	ActorID    uuid.NullUUID
	Action     string
	TargetKind *string
	TargetID   uuid.NullUUID
	Detail     []byte
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorKind,
		arg.ActorID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Detail,
	)
	return err
}

const insertUserToken = `-- name: InsertUserToken :exec
insert into user_tokens (id, user_id, kind, token_hash, expires_at, created_by)
values ($1, $2, $3, $4, $5, $6)
`

type InsertUserTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	TokenHash []byte
	ExpiresAt time.Time
	CreatedBy uuid.NullUUID
}

func (q *Queries) InsertUserToken(ctx context.Context, arg InsertUserTokenParams) error {
	_, err := q.db.Exec(ctx, insertUserToken,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}

const listUserIDs = `-- name: ListUserIDs :many
select id from users order by id
`

func (q *Queries) ListUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockThrottle = `-- name: LockThrottle :one
select failures, blocked_until, updated_at from auth_throttle where key = $1 for update
`

type LockThrottleRow struct {
	Failures     int32
	BlockedUntil *time.Time
	UpdatedAt    time.Time
}

func (q *Queries) LockThrottle(ctx context.Context, key string) (LockThrottleRow, error) {
	row := q.db.QueryRow(ctx, lockThrottle, key)
	var i LockThrottleRow
	err := row.Scan(&i.Failures, &i.BlockedUntil, &i.UpdatedAt)
	return i, err
}

const peekUserToken = `-- name: PeekUserToken :one
select user_id from user_tokens where token_hash = $1 and kind = $2 and used_at is null and expires_at > $3
`

type PeekUserTokenParams struct {
	TokenHash []byte
	Kind      string
	ExpiresAt time.Time
}

// Looks at a token without using it, so that a request with a bad token is refused before any expensive work (SR-003).
func (q *Queries) PeekUserToken(ctx context.Context, arg PeekUserTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, peekUserToken, arg.TokenHash, arg.Kind, arg.ExpiresAt)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const purgeChanges = `-- name: PurgeChanges :execrows
delete from changes where user_id = $1 and created_at < $2
`

type PurgeChangesParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) PurgeChanges(ctx context.Context, arg PurgeChangesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeChanges, arg.UserID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeIngestEvents = `-- name: PurgeIngestEvents :execrows
delete from ingest_events where received_at < $1
`

func (q *Queries) PurgeIngestEvents(ctx context.Context, receivedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeIngestEvents, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeOldNotifications = `-- name: PurgeOldNotifications :execrows
delete from notifications where user_id = $1 and created_at < $2
`

type PurgeOldNotificationsParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) PurgeOldNotifications(ctx context.Context, arg PurgeOldNotificationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldNotifications, arg.UserID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeReadNotifications = `-- name: PurgeReadNotifications :execrows
delete from notifications where user_id = $1 and read_at is not null and read_at < $2
`

type PurgeReadNotificationsParams struct {
	UserID uuid.UUID
	ReadAt *time.Time
}

func (q *Queries) PurgeReadNotifications(ctx context.Context, arg PurgeReadNotificationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeReadNotifications, arg.UserID, arg.ReadAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeThrottle = `-- name: PurgeThrottle :execrows
delete from auth_throttle where updated_at < $1
`

func (q *Queries) PurgeThrottle(ctx context.Context, updatedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeThrottle, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeUnlinkedSenders = `-- name: PurgeUnlinkedSenders :execrows
delete from unlinked_senders where last_notice_at < $1
`

func (q *Queries) PurgeUnlinkedSenders(ctx context.Context, lastNoticeAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeUnlinkedSenders, lastNoticeAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordThrottleFailure = `-- name: RecordThrottleFailure :one
insert into auth_throttle (key, failures, blocked_until, updated_at)
values ($1, 1, null, $2)
on conflict (key) do update set
  failures = case when auth_throttle.updated_at < $3 then 1 else auth_throttle.failures + 1 end,
  updated_at = $2
returning failures
`

type RecordThrottleFailureParams struct {
	Key         string
	UpdatedAt   time.Time
	UpdatedAt_2 time.Time
}

func (q *Queries) RecordThrottleFailure(ctx context.Context, arg RecordThrottleFailureParams) (int32, error) {
	row := q.db.QueryRow(ctx, recordThrottleFailure, arg.Key, arg.UpdatedAt, arg.UpdatedAt_2)
	var failures int32
	err := row.Scan(&failures)
	return failures, err
}

const resetThrottle = `-- name: ResetThrottle :exec
delete from auth_throttle where key = $1
`

func (q *Queries) ResetThrottle(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, resetThrottle, key)
	return err
}

const setThrottle = `-- name: SetThrottle :exec
update auth_throttle set failures = $1, blocked_until = $2, updated_at = $3 where key = $4
`

type SetThrottleParams struct {
	Failures     int32
	BlockedUntil *time.Time
	UpdatedAt    time.Time
	Key          string
}

func (q *Queries) SetThrottle(ctx context.Context, arg SetThrottleParams) error {
	_, err := q.db.Exec(ctx, setThrottle,
		arg.Failures,
		arg.BlockedUntil,
		arg.UpdatedAt,
		arg.Key,
	)
	return err
}

const setThrottleBlock = `-- name: SetThrottleBlock :exec
update auth_throttle set blocked_until = $2 where key = $1
`

type SetThrottleBlockParams struct {
	Key          string
	BlockedUntil *time.Time
}

func (q *Queries) SetThrottleBlock(ctx context.Context, arg SetThrottleBlockParams) error {
	_, err := q.db.Exec(ctx, setThrottleBlock, arg.Key, arg.BlockedUntil)
	return err
}
