// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeUserToken = `-- name: ConsumeUserToken :one
update user_tokens set used_at = $3
where token_hash = $1 and kind = $2 and used_at is null and expires_at > $3
returning user_id
`

type ConsumeUserTokenParams struct {
	TokenHash []byte
	Kind      string
	UsedAt    *time.Time
}

func (q *Queries) ConsumeUserToken(ctx context.Context, arg ConsumeUserTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeUserToken, arg.TokenHash, arg.Kind, arg.UsedAt)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteUserTokens = `-- name: DeleteUserTokens :exec
delete from user_tokens where user_id = $1 and kind = $2
`

type DeleteUserTokensParams struct {
	UserID uuid.UUID
	Kind   string
}

func (q *Queries) DeleteUserTokens(ctx context.Context, arg DeleteUserTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUserTokens, arg.UserID, arg.Kind)
	return err
}

const getThrottle = `-- name: GetThrottle :one
select failures, blocked_until, updated_at from auth_throttle where key = $1
`

type GetThrottleRow struct {
	Failures     int32
	BlockedUntil *time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetThrottle(ctx context.Context, key string) (GetThrottleRow, error) {
	row := q.db.QueryRow(ctx, getThrottle, key)
	var i GetThrottleRow
	err := row.Scan(&i.Failures, &i.BlockedUntil, &i.UpdatedAt)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
insert into audit_log (actor_kind, actor_id, action, target_kind, target_id, detail)
values ($1, $2, $3, $4, $5, $6)
`

type InsertAuditParams struct {
	ActorKind  string
	ActorID    uuid.NullUUID
	Action     string
	TargetKind *string
	TargetID   uuid.NullUUID
	Detail     []byte
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorKind,
		arg.ActorID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Detail,
	)
	return err
}

const insertUserToken = `-- name: InsertUserToken :exec
insert into user_tokens (id, user_id, kind, token_hash, expires_at, created_by)
values ($1, $2, $3, $4, $5, $6)
`

type InsertUserTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	TokenHash []byte
	ExpiresAt time.Time
	CreatedBy uuid.NullUUID
}

func (q *Queries) InsertUserToken(ctx context.Context, arg InsertUserTokenParams) error {
	_, err := q.db.Exec(ctx, insertUserToken,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}

const recordThrottleFailure = `-- name: RecordThrottleFailure :one
insert into auth_throttle (key, failures, blocked_until, updated_at)
values ($1, 1, null, $2)
on conflict (key) do update set
  failures = case when auth_throttle.updated_at < $3 then 1 else auth_throttle.failures + 1 end,
  updated_at = $2
returning failures
`

type RecordThrottleFailureParams struct {
	Key         string
	UpdatedAt   time.Time
	UpdatedAt_2 time.Time
}

func (q *Queries) RecordThrottleFailure(ctx context.Context, arg RecordThrottleFailureParams) (int32, error) {
	row := q.db.QueryRow(ctx, recordThrottleFailure, arg.Key, arg.UpdatedAt, arg.UpdatedAt_2)
	var failures int32
	err := row.Scan(&failures)
	return failures, err
}

const resetThrottle = `-- name: ResetThrottle :exec
delete from auth_throttle where key = $1
`

func (q *Queries) ResetThrottle(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, resetThrottle, key)
	return err
}

const setThrottleBlock = `-- name: SetThrottleBlock :exec
update auth_throttle set blocked_until = $2 where key = $1
`

type SetThrottleBlockParams struct {
	Key          string
	BlockedUntil *time.Time
}

func (q *Queries) SetThrottleBlock(ctx context.Context, arg SetThrottleBlockParams) error {
	_, err := q.db.Exec(ctx, setThrottleBlock, arg.Key, arg.BlockedUntil)
	return err
}
