// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activateUser = `-- name: ActivateUser :execrows
update users set password_hash = $2, status = 'active', updated_at = $3, version = version + 1
where id = $1 and status = 'pending'
`

type ActivateUserParams struct {
	ID           uuid.UUID
	PasswordHash *string
	UpdatedAt    time.Time
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateUser, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearUserPassword = `-- name: ClearUserPassword :exec
update users set password_hash = null, status = 'pending', updated_at = $2, version = version + 1
where id = $1
`

type ClearUserPasswordParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) ClearUserPassword(ctx context.Context, arg ClearUserPasswordParams) error {
	_, err := q.db.Exec(ctx, clearUserPassword, arg.ID, arg.UpdatedAt)
	return err
}

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
insert into users (id, username, display_name, email, timezone, is_admin)
values ($1, $2, $3, $4, $5, $6) returning id, username, display_name, email, status, is_admin, password_hash, timezone, settings, change_seq, created_at, updated_at, version
`

type CreateUserParams struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	Email       *string
	Timezone    string
	IsAdmin     bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Timezone,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Timezone,
		&i.Settings,
		&i.ChangeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const currentChangeSeq = `-- name: CurrentChangeSeq :one
select change_seq from users where id = $1
`

func (q *Queries) CurrentChangeSeq(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, currentChangeSeq, id)
	var change_seq int64
	err := row.Scan(&change_seq)
	return change_seq, err
}

const deleteBlobChunksBatch = `-- name: DeleteBlobChunksBatch :execrows
delete from blob_chunks where (blob_id, idx) in (select c.blob_id, c.idx from blob_chunks c where c.user_id = $1 limit $2) and user_id = $1
`

type DeleteBlobChunksBatchParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) DeleteBlobChunksBatch(ctx context.Context, arg DeleteBlobChunksBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlobChunksBatch, arg.UserID, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserAttachments = `-- name: DeleteUserAttachments :execrows
delete from attachments where user_id = $1
`

func (q *Queries) DeleteUserAttachments(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserAttachments, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserNoteParts = `-- name: DeleteUserNoteParts :execrows
delete from note_parts where user_id = $1
`

func (q *Queries) DeleteUserNoteParts(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserNoteParts, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserRow = `-- name: DeleteUserRow :execrows
delete from users where id = $1 and status = 'deleting'
`

func (q *Queries) DeleteUserRow(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserRow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureUserStorage = `-- name: EnsureUserStorage :exec
insert into user_storage (user_id) values ($1) on conflict do nothing
`

func (q *Queries) EnsureUserStorage(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureUserStorage, userID)
	return err
}

const getAdmin = `-- name: GetAdmin :one
select id, username, display_name, email, status, is_admin, password_hash, timezone, settings, change_seq, created_at, updated_at, version from users where is_admin
`

func (q *Queries) GetAdmin(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, getAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Timezone,
		&i.Settings,
		&i.ChangeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, username, display_name, email, status, is_admin, password_hash, timezone, settings, change_seq, created_at, updated_at, version from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Timezone,
		&i.Settings,
		&i.ChangeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, display_name, email, status, is_admin, password_hash, timezone, settings, change_seq, created_at, updated_at, version from users where lower(username) = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Timezone,
		&i.Settings,
		&i.ChangeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const identitiesForDeletion = `-- name: IdentitiesForDeletion :many
select bot_instance_id, external_user_id, conversation_id from external_identities where user_id = $1 and conversation_id is not null
`

type IdentitiesForDeletionRow struct {
	BotInstanceID  uuid.UUID
	ExternalUserID string
	ConversationID *string
}

func (q *Queries) IdentitiesForDeletion(ctx context.Context, userID uuid.UUID) ([]IdentitiesForDeletionRow, error) {
	rows, err := q.db.Query(ctx, identitiesForDeletion, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentitiesForDeletionRow{}
	for rows.Next() {
		var i IdentitiesForDeletionRow
		if err := rows.Scan(&i.BotInstanceID, &i.ExternalUserID, &i.ConversationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChange = `-- name: InsertChange :exec
insert into changes (user_id, seq, entity_type, entity_id, op, version)
values ($1, $2, $3, $4, $5, $6)
`

type InsertChangeParams struct {
	UserID     uuid.UUID
	Seq        int64
	EntityType string
	EntityID   uuid.UUID
	Op         string
	Version    *int32
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) error {
	_, err := q.db.Exec(ctx, insertChange,
		arg.UserID,
		arg.Seq,
		arg.EntityType,
		arg.EntityID,
		arg.Op,
		arg.Version,
	)
	return err
}

const listChanges = `-- name: ListChanges :many
select seq, entity_type, entity_id, op, version from changes
where user_id = $1 and seq > $2 order by seq limit $3
`

type ListChangesParams struct {
	UserID uuid.UUID
	Seq    int64
	Limit  int32
}

type ListChangesRow struct {
	Seq        int64
	EntityType string
	EntityID   uuid.UUID
	Op         string
	Version    *int32
}

func (q *Queries) ListChanges(ctx context.Context, arg ListChangesParams) ([]ListChangesRow, error) {
	rows, err := q.db.Query(ctx, listChanges, arg.UserID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChangesRow{}
	for rows.Next() {
		var i ListChangesRow
		if err := rows.Scan(
			&i.Seq,
			&i.EntityType,
			&i.EntityID,
			&i.Op,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletingUsers = `-- name: ListDeletingUsers :many
select id from users where status = 'deleting' order by updated_at limit 50
`

func (q *Queries) ListDeletingUsers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDeletingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
select u.id, u.username, u.display_name, u.status, u.is_admin, u.created_at,
       coalesce(s.used_bytes, 0)::bigint as used_bytes, s.quota_bytes
from users u left join user_storage s on s.user_id = u.id
order by lower(u.username)
`

type ListUsersRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	Status      string
	IsAdmin     bool
	CreatedAt   time.Time
	UsedBytes   int64
	QuotaBytes  *int64
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Status,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UsedBytes,
			&i.QuotaBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
select id, status, is_admin from users where id = $1 for update
`

type LockUserRow struct {
	ID      uuid.UUID
	Status  string
	IsAdmin bool
}

func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (LockUserRow, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i LockUserRow
	err := row.Scan(&i.ID, &i.Status, &i.IsAdmin)
	return i, err
}

const nextChangeSeq = `-- name: NextChangeSeq :one
update users set change_seq = change_seq + 1 where id = $1 returning change_seq
`

func (q *Queries) NextChangeSeq(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextChangeSeq, id)
	var change_seq int64
	err := row.Scan(&change_seq)
	return change_seq, err
}

const oldestChangeSeq = `-- name: OldestChangeSeq :one
select coalesce(min(seq), 0)::bigint from changes where user_id = $1
`

func (q *Queries) OldestChangeSeq(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, oldestChangeSeq, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setAdmin = `-- name: SetAdmin :exec
update users set is_admin = $2, updated_at = $3, version = version + 1 where id = $1
`

type SetAdminParams struct {
	ID        uuid.UUID
	IsAdmin   bool
	UpdatedAt time.Time
}

func (q *Queries) SetAdmin(ctx context.Context, arg SetAdminParams) error {
	_, err := q.db.Exec(ctx, setAdmin, arg.ID, arg.IsAdmin, arg.UpdatedAt)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
update users set password_hash = $2, updated_at = $3, version = version + 1 where id = $1
`

type SetPasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash *string
	UpdatedAt    time.Time
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	return err
}

const setQuota = `-- name: SetQuota :exec
update user_storage set quota_bytes = $2 where user_id = $1
`

type SetQuotaParams struct {
	UserID     uuid.UUID
	QuotaBytes *int64
}

func (q *Queries) SetQuota(ctx context.Context, arg SetQuotaParams) error {
	_, err := q.db.Exec(ctx, setQuota, arg.UserID, arg.QuotaBytes)
	return err
}

const setUserStatus = `-- name: SetUserStatus :exec
update users set status = $2, updated_at = $3, version = version + 1 where id = $1
`

type SetUserStatusParams struct {
	ID        uuid.UUID
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
update users set display_name = coalesce($1, display_name),
  timezone = coalesce($2, timezone), settings = coalesce($3::jsonb, settings),
  updated_at = $4, version = version + 1
where id = $5 returning id, username, display_name, email, status, is_admin, password_hash, timezone, settings, change_seq, created_at, updated_at, version
`

type UpdateProfileParams struct {
	DisplayName *string
	Timezone    *string
	Settings    []byte
	UpdatedAt   time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.DisplayName,
		arg.Timezone,
		arg.Settings,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Timezone,
		&i.Settings,
		&i.ChangeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
